#!/bin/csh -f
#
# CSH-TEMPLATE - CSH script template with lots of boiler plate
#
# include cpyright.h
#

unalias *

@ err = 0

while ($#argv > 0)
   switch ($1)
      case -h:
           echo ""
           echo "Usage: xxx [-h]"
           echo "   h   this help message"
           echo ""
           echo ""
           exit(1)
      default:
           breaksw
   endsw
   shift
end

exit($err)
