#!/bin/csh -f
#
# SCS-TAG - tag a version whether GIT, CVS or SVN
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

unalias *

set ldir = `dirname $0`
if ("$ldir" == ".") then
   set ldir = $cwd
endif
set scsi = ( `$ldir/which-scs` )
unset ldir

switch ($scsi[1])
   case git:
        git tag $argv
        breaksw

   case cvs:
        setenv CVS_RSH  ssh
        cvs tag $argv
# example: cvs rtag $TagID $codename doc test
        breaksw

   case svn:
        svn tag $argv
        breaksw
endsw

exit($status)
