#!/bin/csh -f
#
# SRTEST - test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

setenv Package scripts
setenv Test    ""
set vgdirs = ""
source ../scripts/test-env

set Tests = ""

while ($#argv > 0)
   switch ($1)
      case -h:
           echo ""
           echo "Usage: srtest [-f] [-h] [<test>*]"
           echo "  f  force the tests to be run"
           echo "  h  this help message"
           echo ""
           exit(1);
      case -f:
           unsetenv RUN_TESTS
           set RUN_TESTS = TRUE
           breaksw
      case -*:
           breaksw
      default:
           set Tests = ( $1 )
           breaksw
   endsw
   shift
end

flog $Log cd $TestDir

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# omit tests - usually in difficult CROSS_COMPILE situation

if ($RUN_TESTS == FALSE) then
   NoteD $Log ""
   NoteD $Log "SCRIPT TESTS ... omitted"

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# run the tests

else if (-e $BaseDir/score/scstd.h) then

   NoteD $Log ""
   NoteD $Log "SCRIPT TEST ..."

   if ("$Tests" == "") then
      set Tests = ""
      set Tests = ($Tests dobatch fnc subr cpp iapi)
   endif

   foreach i ($Tests)
      echo ""
      $FilesDir/$i
      @ nerr = $nerr + $status
   end

   $TEST_CHECK clean -n SCRIPT -e $nerr

   set xstatus = $status

endif

$TEST_CHECK fin -e $xstatus

exit($status)

