#!/bin/csh -f
#
# CC-INLINE - analyze inline for C compiler
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/pre-common

Note $ALog "----- analyze/cc-inline -----"
Note $ALog "Analyze: inline handling"
Note $ALog ""

dbmget $ALog PACT_CC_VERSION

cat << EOF >! $Tmp.c
inline int b(int y)
   {int x;
    x = y % 2;
    return(x);}
int main(int c, char **v)
   {int x, y;
    y = 8;
    x = b(y);
    return(0);}
EOF

flog $ALog $lCC $Tmp.c -o $Tmp
if ($status == 0) then
   setenv HAVE_INLINE TRUE
   NoteD $ALog "      has inline support"
else
   setenv HAVE_INLINE FALSE
   NoteD $ALog "      no inline support"
endif

rm -f $Tmp $Tmp.c $Tmp.o

# export the result
dbexp HAVE_INLINE

source $Me:h/post-common

exit(0)
