#!/bin/csh -f
#
# CSH - analyze the platform C Shell
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/common

Separator $Log
Note $Log "Analyze: csh"

set inf = ( `ls -l /bin/csh` )
@ n = $#inf
echo "$inf" | grep -e '->'
if ($status == 0) then
   set exe = ( `which $inf[$n]` )
else
   set exe = "/bin/csh"
endif

NoteD $ALog -n "   CSH: $exe "
Note $ALog ""

Note $ALog "cwd    = |$cwd|"
Note $ALog "MngDir = |$MngDir|"
Note $ALog "AnaDir = |$AnaDir|"
source $AnaDir/backslash

if ("$BackSlash" == "\") then
   NoteD $ALog "(uses \)"
else
   NoteD $ALog "(uses \\\\)"
endif

SetParent BackSlash

exit(0)
