#!/bin/csh -f
#
# DEFAULT-BITS - figure out default address size
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

if (-f ../scripts/functions-pact.csh) then
   set SrcDir = $cwd
else if (-f ../../scripts/functions-pact.csh) then
   set SrcDir = $cwd:h
endif
set ldir = $SrcDir:h/scripts
set path = ( $ldir $path )
source $ldir/functions-pact.csh

if ($?Bits == 0) then
   setenv Bits `nbit -d`
endif

envexp Bits

exit($status)


