#!/bin/csh -f
#
# DP - analyze distributed parallel options
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/common

if ($?ALog == 1) then
   Note $ALog "Analyze: dp"
endif

NoteD $ALog -n "   Parallel Communication Support: "
Note $ALog ""

$AnaDir/mpi

exit(0)

