#!/bin/csh -f
#
# FINISH - final environment adjustments
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/common

Separator $Log
Note $Log "Analyze: finish"

set vl = ""
set vl = ( $vl GRAPHICS_Windows )
set vl = ( $vl Std_UseX Std_UseOGL Std_UseQD )
set vl = ( $vl AbsoluteDeb MDG_Inc )
set vl = ( $vl CC_Exe CC_Flags CC_Optimize CC_Debug )
set vl = ( $vl FC_Optimize FC_Debug )
set vl = ( $vl Save_CC Save_CFLAGS )
set vl = ( $vl Cfe_CC_Inc )

source $MngDir/write/import-db

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

if ($Std_UseX == FALSE) then

# have OpenGL
   if ($Std_UseOGL == "TRUE") then
      flog $ALog setenv GRAPHICS_Windows OGL

# have Quickdraw
   else if ($Std_UseQD == "TRUE") then
      flog $ALog setenv GRAPHICS_Windows QD

# no screen graphics
   else
      flog $ALog setenv GRAPHICS_Windows       ""
      flog $ALog setenv Std_UseX   FALSE
      flog $ALog setenv Std_UseOGL FALSE
      flog $ALog setenv Std_UseQD  FALSE

      dbexp Std_UseX
      dbexp Std_UseOGL
      dbexp Std_UseQD
   endif

   dbexp GRAPHICS_Windows

endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

if ("$Cfe_CC_Inc" == "$RootInc") then
   flog $ALog setenv Cfe_CC_Inc ""
endif

# NOTE: compilers look at /usr/include by default not
# necessarily $RootInc
dbini MDG_Inc ""
if ("$MDG_Inc" == "-I/usr/include") then
   flog $ALog setenv MDG_Inc ""
endif
dbexp MDG_Inc

if ($?Save_CC == 1) then
   flog $ALog setenv CC_Exe "$Save_CC"
endif

set tmp = ($Save_CFLAGS)
flog $ALog setenv CC_Flags "$tmp"

flog $Log setenv CC_Optimize_Default "$CC_Optimize"
flog $Log setenv CC_Debug_Default    "$CC_Debug"
flog $Log setenv FC_Optimize_Default "$FC_Optimize"
flog $Log setenv FC_Debug_Default    "$FC_Debug"

if ($AbsoluteDeb == TRUE) then
   flog $Log setenv CC_Optimize_Default "$CC_Debug"
   flog $Log setenv FC_Optimize_Default "$FC_Debug"
else if ($AbsoluteOpt == TRUE) then
   flog $Log setenv CC_Debug_Default "$CC_Optimize"
   flog $Log setenv FC_Debug_Default "$FC_Optimize"
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# export the results
dbexp CC_Debug_Default
dbexp CC_Optimize_Default
dbexp FC_Debug_Default
dbexp FC_Optimize_Default

dbexp CC_Exe
dbexp CC_Flags
envexp Cfe_CC_Inc

exit(0)

