#!/bin/csh -f
#
# LIBM - analyze options for libm.a
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/common

Separator $Log
Note $Log "Analyze: libm"

dbini IMF_Lib      "-limf"
dbini IMF_Path     ""
dbini LibM_Lib     "-lm"
dbini LibM_RPath   ""
dbini MD_Pck       ""
dbini Cfg_RPATH    ""

set vl = ""
set vl = ( $vl RPATH )
source $MngDir/write/import-db

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# Intel Math library

if (-d "$IMF_Path") then
   set nbits = `nbit -d`

   fexvars $ALog t ls -rt $IMF_Path/ic*/lib/libimf.a @b grep -v beta @o tail -n 1
else
   set t = ""
endif

Note $ALog "IMF_Path = |$IMF_Path|"
Note $ALog "t        = |$t|"

if (-f "$t") then
   set root = $t:h
   flog $ALog setenv IMF_Path $root
else
   flog $ALog setenv IMF_Path ""
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# figure out the math library situation

if ("$IMF_Path" != "") then
   flog $ALog setenv RPATH         ${RPATH}:${IMF_Path}
   flog $ALog setenv Cfg_RPATH     ${Cfg_RPATH}:${IMF_Path}
   flog $ALog setenv MD_Pck        "$MD_Pck LibM"
   flog $ALog setenv LibM_Lib      "${IMF_Lib}"
   flog $ALog setenv LibM_RPath    ${IMF_Path}

else
   flog $ALog setenv LibM_Lib      "-lm"

endif
NoteD $ALog "   Math library: $LibM_Lib"

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

dbexp MD_Pck
dbexp IMF_Path
dbexp RPATH
dbexp LibM_Lib
dbexp LibM_RPath
dbexp Cfg_RPATH

exit(0)

