#!/bin/csh -f
#
# RUSAGE - analyze platform resource usage
#        - Computes: HAVE_RESOURCE_USAGE
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/pre-common

Note $ALog "Analyze: resource usage"

dbmget $ALog CC_Exe^          \
             CC_Flags^        \
             PACT_CC_VERSION

cat << EOF >! $Tmp.c
#include <sys/resource.h>
int main(int c, char **v)
   {int rv;
    struct rusage r;
    rv = getrusage(RUSAGE_SELF, &r);
    return(rv);}
EOF

setenv HAVE_RESOURCE_USAGE FALSE

flog $ALog $CC_Exe $Tmp.c -o $Tmp $CC_Flags
if ($status == 0) then
   setenv HAVE_RESOURCE_USAGE TRUE
   flog $ALog rm -f $Tmp.c $Tmp
endif

if ($HAVE_RESOURCE_USAGE == FALSE) then
   NoteD $ALog "      no resource usage"
else
   NoteD $ALog "      has resource usage"
endif

dbexp HAVE_RESOURCE_USAGE

source $Me:h/post-common

exit(0)

