#!/bin/csh -f
#
# SH - analyze the platform Bourne Shell
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/pre-common

Note $ALog "----- analyze/sh -----"
Note $ALog "Analyze: Bourne shell"
Note $ALog ""

setenv SHELL_Default ""

foreach i ($path /usr/bin /bin)
   if (-x $i/bash) then
      NoteD $ALog "   SH: $i/bash"
      setenv SHELL_Default $i/bash
      dbexp SHELL_Default
      exit(0)
   endif
end

foreach i ($path /usr/bin /bin)
   if (-x $i/sh) then
      NoteD $ALog "   SH: $i/sh"
      setenv SHELL_Default $i/sh
      dbexp SHELL_Default
      exit(0)
   endif
end

dbexp SHELL_Default

source $Me:h/post-common

exit(1)
