#!/bin/csh -f
#
# SITE - analyze and set site information
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/common

Separator $Log
Note $Log "Analyze: site"

dbmget $ALog SYS_SITE =\? ""^  \
             SYS_TYPE =\? ""^  \
             DAI_ROOT =\? ""^  \
             DAS_ROOT =\? ""

if ($?SITE_SIGNATURE_DB == 1) then
   Note $Log "SITE_SIGNATURE_DB = $SITE_SIGNATURE_DB"
else
   Note $Log "SITE_SIGNATURE_DB not defined"
endif

if (-f $MngDir/extensions/sys-site) then
   eval `$MngDir/extensions/sys-site`
else
   eval `$ScrDir/sys-site -dc`
endif

# export the results
dbmset $ALog SYS_SITE = $SYS_SITE^  \
             SYS_TYPE = $SYS_TYPE^  \
             DAI_ROOT = $DAI_ROOT^  \
             DAS_ROOT = $DAS_ROOT

exit(0)

