#!/bin/csh -f
#
# SITE - analyze and set site information
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/common

Note $ALog "Analyze: site"

dbmget $ALog SYS_SITE   =\? ""^  \
             SYS_TYPE   =\? ""^  \
             SYS_AIRoot =\? ""^  \
             SYS_ASRoot =\? ""

if ($?DB_SITE_SIGNATURE == 1) then
   Note $ALog "DB_SITE_SIGNATURE = $DB_SITE_SIGNATURE"
else
   Note $ALog "DB_SITE_SIGNATURE not defined"
endif

if (-f $MngDir/extensions/sys-site) then
   eval `$MngDir/extensions/sys-site`
else
   eval `$ScrDir/sys-site -dc`
endif

# export the results
dbmset $ALog SYS_SITE   = $SYS_SITE^    \
             SYS_TYPE   = $SYS_TYPE^    \
             SYS_AIRoot = $SYS_AIRoot^  \
             SYS_ASRoot = $SYS_ASRoot

exit(0)

