#!/bin/csh -f
#
# SOCKET - analyze the handling of sockets
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/pre-common

Note $ALog "----- analyze/socket -----"
Note $ALog "Analyze: socket handling"
Note $ALog ""

dbmget $ALog HAVE_SOCKETS =\? TRUE^ \
             Cfe_CC_Exe^            \
             Cfe_CC_Flags^          \
             Cfe_LD_Flags^          \
             Cfe_LD_Lib^            \
             Cfe_LD_RPath^          \
             PACT_CC_VERSION

cat << EOF >! $Tmp.c
#include <sys/socket.h>
int main(int c, char **v)
{int iv, nb;
 getsockopt(NULL, 0, 0, &iv, &nb);
 return(0);}
EOF

set opt = ""
set opt = ( $opt $Cfe_CC_Flags )
set opt = ( $opt $Cfe_LD_Flags $Cfe_LD_RPath )

fexvars $ALog t $Cfe_CC_Exe $Tmp.c -o $Tmp $opt @b wc -l
Note $ALog "t = |$t|"
if ($t == 0) then
   flog $ALog setenv AF_SOCKOPT_TYPE "int"
else
   flog $ALog setenv AF_SOCKOPT_TYPE "unsigned int"
endif
unset t

NoteD $ALog "      getsockopt type: $AF_SOCKOPT_TYPE"

flog $ALog rm -f $Tmp.c $Tmp

# export the results
dbmset $ALog HAVE_SOCKETS    = $HAVE_SOCKETS^    \
             AF_SOCKOPT_TYPE = $AF_SOCKOPT_TYPE

source $Me:h/post-common

exit(0)

