#!/bin/csh -f
#
# CSOLV - PML conjugate gradient solver tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PML CG Solver Test ....."
set exe = $BinDir/tmlcg
set opt = ""
set io  = flog

   NoteD $Log ""
   NoteD $Log -n "                    $msg"

   flog $Log pushd $SrcDir
   flog $Log $MAKE cgsolv
   set xstatus = $status
   flog $Log popd

   if ($xstatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         Can't build PML CG Solver Test Program"
   else
      source ../../../scripts/test-run
   endif

$TEST_CHECK part -a cgsolv -e $xstatus -dt $dt -x $exe none

exit($status)

