#!/bin/csh -f
#
# CSOLV - PML conjugate gradient solver tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PML CG Solver Test ..... "
set rpf = "none"
set exe = $BinDir/mlcgts

   NoteD $Log ""
   NoteD $Log -n "                    $msg"

   set FAIL = "NO"

   flog $Log pushd $SrcDir
   flog $Log $MAKE cgsolv
   set TStatus = $status
   flog $Log popd

   set UTime = `$TIMER -r`

   if ($TStatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         Can't build PML CG Solver Test Program"
      set xstatus = $TStatus
   else
      if ("$Valgrind" == "") then
         flog $LogF $cfe $exe
         set xstatus = $status
      else
         flog $Log $Valgrind $exe
         set xstatus = $status
      endif
   endif

$TEST_CHECK part -a cgsolv -e $xstatus -x $exe none

exit($status)

