#!/bin/csh -f
#
# COMMON - support for PML test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../../scripts/env-csh

if ($?LogF == 0) then
   set TestName = "$0:t"

   InitLog LogF $cwd/log.$TestName.$LogSfx
   pushd ../../../manager >& /dev/null
   set Arch = `cfgman use`
   cd ../dev/$Arch >& /dev/null
   set Root = $cwd
   popd >& /dev/null

   set BinDir   = $Root/bin
   set LibDir   = $Root/lib
   set MAKE     = $BinDir/pact
   set TIMER    = $BinDir/timer
   set CFE      = $BinDir/do-run
   set PFE      = $BinDir/do-run
endif

set RefDir = ../../../pml/tests/ref

if ($?SrcDir == 0) then
   pushd ../.. >& /dev/null
   set SrcDir = $cwd
   popd >& /dev/null
endif

if ($?Log == 1) then
   Note $Log "Log file: $LogF"
endif

set Err = 0

