#!/bin/csh -f
#
# EIGEN - PML eigen system tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PML Eigen Test ......... "
set rpf = "none"
set exe = $BinDir/mlevts

   NoteD $Log ""
   NoteD $Log  -n "                    $msg"

   flog $Log pushd $SrcDir
   flog $Log $MAKE eigen
   set TStatus = $status
   flog $Log popd

   if ($TStatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         Can't build PML Eigen Test Program"
      set xstatus = $TStatus
   else
      if ("$Valgrind" == "") then
         flog $LogF $cfe $exe
         set xstatus = $status
      else
         flog $Log $Valgrind $exe
         set xstatus = $status
      endif
   endif

$TEST_CHECK part -a eigen -e $xstatus -x $exe none

exit($status)


