#!/bin/csh -f
#
# EIGEN - PML eigen system tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

#--------------------------------------------------------------------------

#                             PML EIGEN TEST

#--------------------------------------------------------------------------

   NoteD $Log ""
   NoteD $Log  -n "                    PML Eigen Test ......... "

   flog $Log pushd $SrcDir
   flog $Log $MAKE eigen
   set TStatus = $status
   flog $Log popd

   set UTime = `$TIMER -r`

   if ($TStatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         Can't build PML Eigen Test Program"
      set xstatus = $TStatus
   else
      if ("$Valgrind" == "") then
         flog $LogF $cfe $BinDir/mlevts
         set xstatus = $status
      else
         flog $Log $Valgrind $BinDir/mlevts
         set xstatus = $status
      endif
      if ($xstatus != 0) then
        NoteD $Log ""
        NoteD $Log "                         Error in Eigen Test program"
      endif
   endif

   set ETime = `$TIMER -b $UTime`

   if (($xstatus == 254) || ($xstatus == 255)) then
      NoteD $Log  "                    PML Eigen Test ......... OMITTED ($xstatus/$ETime)"
   else if ($xstatus != 0) then
      NoteD $Log  "                    PML Eigen Test ......... FAILED ($ETime)"
      @ Err = 1
   else
      NoteD $Log "PASSED ($ETime)"
   endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK -a eigen -e $Err part

exit($status)


