#!/bin/csh -f
#
# MATRIX - PML matrix tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PML Matrix Test ........"
set exe = $BinDir/tmlmtx
set opt = ""
set io  = flog

   NoteD $Log ""
   NoteD $Log  -n "                    $msg"

   flog $Log pushd $SrcDir
   flog $Log $MAKE matrix
   set xstatus = $status
   flog $Log popd

   if ($xstatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         Can't build PML Matrix Test Program"
   else
      source ../../../scripts/test-run
   endif

$TEST_CHECK part -a matrix -e $xstatus -dt $dt -x $exe none

exit($status)


