#!/bin/csh -f
#
# PERF - PML performance tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PML Performance Test ... "
set exe = $BinDir/mlpfts
set opt = ""
set io  = flog

   set OD = ( `pact +l -info OD` )
   if ("$OD" == DefaultO) then
      NoteD $Log ""
      NoteD $Log "                    $msg"

      flog $Log pushd $SrcDir
      flog $Log $MAKE perf
      set xstatus = $status
      flog $Log popd

      if ($xstatus != 0) then
         NoteD $Log ""
         NoteD $Log "                         Can't build PML Performance Test Program"
      else
         source ../../../scripts/test-run
      endif

      $TEST_CHECK part -a perf -e $xstatus -dt $dt -x $exe none

      set xstatus = $status
   endif

exit($xstatus)

