#!/bin/csh -f
#
# SOLV - PML matrix solver tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PML Solver Test ........ "
set exe = $BinDir/mlicts

   NoteD $Log ""
   NoteD $Log -n "                    $msg"

   set FAIL = "NO"

   flog $Log pushd $SrcDir
   flog $Log $MAKE icsolv
   set xstatus = $status
   flog $Log popd

   if ($xstatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         Can't build PML Solver Test Program"
   else
      if ("$Valgrind" == "") then
         flog $LogF $cfe $exe
         set xstatus = $status
      else
         flog $Log $Valgrind $exe
         set xstatus = $status
      endif
   endif

$TEST_CHECK part -a solv -e $xstatus -x $exe none

exit($status)

