#!/bin/csh -f
#
# CONFIGURED - write the CONFIGURED file
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

unalias *

# put these in shell variables since
# prune-env will remove them as environment variables
set Log    = $1
set ScrDir = $2
set lCfg   = $3

eval `$ScrDir/prune-env -e DbgOpt pact`
set path = ( $ScrDir $path )
source $ScrDir/env-csh

dbget IncDir

# NOTE: must dbset this in dsys first
#dbget DbgOpt

dbget USER
dbget Host
dbget HostOS
dbget HAVE_JPEGLIB
dbget HAVE_PNGLIB
dbget UseTmpDir
dbget FilterDir
dbget WARN_PATTERN
dbget ERR_PATTERN

Separator $Log
Note $Log "   IncDir       = $IncDir"
Note $Log "   DbgOpt       = $DbgOpt"
Note $Log "   USER         = $USER"
Note $Log "   Host         = $Host"
Note $Log "   HostOS       = $HostOS"
Note $Log "   HAVE_JPEGLIB = $HAVE_JPEGLIB"
Note $Log "   HAVE_PNGLIB  = $HAVE_PNGLIB"
Note $Log "   UseTmpDir    = $UseTmpDir"
Note $Log "   FilterDir    = $FilterDir"
Note $Log "   WARN_PATTERN = $WARN_PATTERN"
Note $Log "   ERR_PATTERN  = $ERR_PATTERN"

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

    NoteD $Log "   Configuration record - configured"

    set STDOUT = $IncDir/configured

    flog $Log $RM $STDOUT
    flog $Log touch $STDOUT

    Note $STDOUT "Config       = $lCfg"
    Note $STDOUT "DbgOpt       = $DbgOpt"
    Note $STDOUT "User         = $USER"
    Note $STDOUT "Date         = `date`"
    Note $STDOUT "Host         = $Host"
    Note $STDOUT "OS           = $HostOS"
    if ("$HAVE_JPEGLIB" == "") then
       Note $STDOUT "JPEG         = no"
    else
       Note $STDOUT "JPEG         = yes"
    endif

    if ("$HAVE_PNGLIB" == "") then
       Note $STDOUT "PNG          = no"
    else
       Note $STDOUT "PNG          = yes"
    endif

    if (-f $lCfg) then
       set Shared = `grep Shared $lCfg`
       if ("$Shared" == "") then
          Note $STDOUT "Shared       = no"
       else
          Note $STDOUT "Shared       = yes"
       endif
    endif

    Note $STDOUT "UseTmpDir    = $UseTmpDir"
    Note $STDOUT "FilterDir    = $FilterDir"
    Note $STDOUT "WARN_PATTERN = $WARN_PATTERN"
    Note $STDOUT "ERR_PATTERN  = $ERR_PATTERN"

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

exit(0)

