#!/bin/csh -f
#
# PACKAGE - write the PACKAGE file
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

unalias *

if (-f ../scripts/env-csh) then
   set SrcDir = $cwd
else if (-f ../../scripts/env-csh) then
   set SrcDir = $cwd:h
endif
set ldir = $SrcDir:h/scripts
set path = ( $ldir $path )
source $ldir/env-csh

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

    Separator $Log
    NoteD $Log "   Package List - package"

    set STDOUT = $IncDir/package

    flog $Log $RM $STDOUT
    flog $Log touch $STDOUT

    set Pkgs = ( `awk '$1 == "pkg" {for (i = 2; i <= NF; i++) {printf("%s ", $i);};}' pact.manifest` )

# must have one package per line because dmake needs it that way
    foreach i ($Pkgs)
       if ($i == python) then
          if (($HavePython == TRUE) && ($HavePythonNumpy == TRUE)) then
             echo "$i" >>& $STDOUT
          endif
       else if ($i == pya) then
          if (($HavePython == TRUE) && ($HavePythonNumeric == TRUE)) then
             echo "$i" >>& $STDOUT
          endif
       else
          echo "$i" >>& $STDOUT
       endif
    end

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

exit(0)

