#!/bin/csh -f
#
# COMMON - support for PANACEA test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

setenv Package  panacea
setenv Test     $0:t
source $PSY_Base/scripts/test-env

if ("$CROSS_FE" == "") then
   set cross_fe = ""
else
   set cross_fe = ( $CROSS_FE -v )
endif

