#!/bin/csh -f
#
# AXIS - ULTRA AXIS test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "ULTRA AXIS Test .............. "
set exe = $BinDir/ultra
set opt = ( -e -r -x -q -s $ZeroSpace -l $TDir/ulaxs.scm )
set io  = ulaxs.log

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log $RM ulaxs.log ulaxs.err

   source ../../../scripts/test-run

   flog $Log ($CFE $PSDIFF ulaxs.ps $RefDir/ulaxs.ps >&! ulaxs.ps.diff)

   set rpf = ( $rpf ulaxs.* )

$TEST_CHECK part -a fill -e $xstatus -rpf "$rpf" none

exit($status)
