#!/bin/csh -f
#
# AXIS - ULTRA AXIS test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

#--------------------------------------------------------------------------

#                           AXIS TEST

#--------------------------------------------------------------------------

   NoteD $Log ""
   NoteD $Log -n "                    ULTRA AXIS Test .............. "
   Note $Log ""

   flog $Log $RM ulaxs.log ulaxs.err

   set rpf = ""

   if ("$Valgrind" == "") then
      flog $Log ($CFE $Ultra -l $TDir/ulaxs.scm >& ulaxs.log)
      set xstatus = $status
      flog $Log ($CFE $PSDIFF ulaxs.ps $RefDir/ulaxs.ps >&! ulaxs.ps.diff)
   else
      ftee $Log $Valgrind $BinDir/ultra -e -r -x -q -s -l $TDir/ulaxs.scm  |& \
      grep "ERROR SUMMARY:"                                                |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set prf     = ( $prf $Tmp )
   endif

   set rpf = ( $rpf ulaxs.* )

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK part -a fill -e $xstatus -rpf "$rpf" none

exit($status)
