#!/bin/csh -f
#
# FNC - ULTRA function test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "ULTRA FNC Test ............... "
set exe = $BinDir/ultra

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log $RM ultest.err ulfnc.log

   set opt = ( -l $TDir/ulfnc.scm )
   if ("$Valgrind" == "") then

# CYGWIN 1.5 simply will not write output to ulfnc.log
# the other tests are fine
      if ($OS =~ CYGWIN*) then
         flog $Log $cfe $Ultra $opt
         set xstatus = $status
      else
         flog $Log ($CFE $Ultra $opt >&! ulfnc.log)
         set xstatus = $status
         flog $Log (grep -i "error" ulfnc.log >&! ultest.err)
         set Files = `find . -name "ultest.err" -size 0c -print`
      endif
   else
      ftee $Log $Valgrind $exe -e -r -x -q -s $opt     |& \
      grep "ERROR SUMMARY:"                            |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = $Tmp
   endif

$TEST_CHECK part -a fnc -e $xstatus -rpf "$rpf" none

exit($status)
