#!/bin/csh -f
#
# MEM - ULTRA memory test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

#--------------------------------------------------------------------------

#                           MEMORY TEST

#--------------------------------------------------------------------------

   NoteD $Log ""
   NoteD $Log -n "                    ULTRA Memory Test ............ "
   Note $Log ""

   set UTime = `$TIMER -r`
   if ("$Valgrind" == "") then
      flog $Log ($CFE $Ultra -n -l $TDir/ulmmt.scm >& ulmmt.log)
      set xstatus = $status
   else
      ftee $Log $Valgrind $BinDir/ultra -e -r -x -q -s -l $TDir/ulmmt.scm  |& \
      grep "ERROR SUMMARY:"                                                         |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      flog $Log $RM $Tmp
   endif

   set ETime = `$TIMER -b $UTime`

   if (($xstatus == 254) || ($xstatus == 255)) then
      NoteD $LogF "OMITTED ($xstatus/$ETime)"
   else if ($xstatus != 0) then
      NoteD $Log "FAILED ($xstatus/$ETime)"
      set Err = 1
   else
      NoteD $Log "PASSED ($ETime)"
   endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

exit($Err)
