#!/bin/csh -f
#
# MEM - ULTRA memory test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "ULTRA Memory Test ............ "

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   if ("$Valgrind" == "") then
      flog $Log ($CFE $Ultra -n -l $TDir/ulmmt.scm >& ulmmt.log)
      set xstatus = $status
   else
      ftee $Log $Valgrind $BinDir/ultra -e -r -x -q -s -l $TDir/ulmmt.scm  |& \
      grep "ERROR SUMMARY:"                                                         |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

$TEST_CHECK part -a mem -e $xstatus -rpf "$rpf" none

exit($status)
