#!/bin/csh -f
#
# AXIS - SX AXIS test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/sx/tests/common

set msg = "SX PGS Axis Test ............."
set exe = $BinDir/sx
set opt = ( $sxopt -l $FilesDir/sxaxs.scm )
set io  = flog

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   source $PSY_Base/scripts/test-run

   if ($xstatus == 0) then
      flog $Log ( $CROSS_FE $PSDIFF sxaxs.ps $RefDir/sxaxs.ps > sxaxs.ps.diff )
      set xstatus = $status
   endif

   touch sxaxs.foo
   set rpf = ( $rpf sxaxs.* )
   rm -f sxaxs.foo

$TEST_CHECK part -a axis -e $xstatus -dt $dt -rpf "$rpf" none

exit($status)
