#!/bin/csh -f
#
# PGS - SX PGS test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/sx/tests/common

set msg = "SX PGS Test .................."
set exe = $BinDir/sx
set opt = ( $sxopt -l $FilesDir/sxpgs.scm )
set io  = sxpgs.res

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   source $PSY_Base/scripts/test-run

   if (($xstatus == 0) && ("$Valgrind" == "")) then
      flog $Log $cross_fe $PSDIFF sxpgs.ps $FilesDir/ref/sxpgs.ps
      set xstatus = $status
   endif

   set rpf = ( $rpf sxpgs.ps )

$TEST_CHECK part -a pgs -e $xstatus -dt $dt -rpf "$rpf" none

exit($status)
