#!/bin/csh -f
#
# SHELL - PDBVIEW shell tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDBView Shell Test ..........."
set exe = $BinDir/sx

   NoteD $Log ""
   if (($CROSS_COMPILE == FALSE) && ($HaveIPC == YES)) then
      NoteD $Log "                    $msg"

# env test
      NoteD $Log -n "                       env ......................."
      set rpf = none

      set t0 = `$TIMER -r`

      $CROSS_FE $FilesDir/pdbvenv.scm >&! pdbvenv.res
      set xstatus = $status

      set dt = `$TIMER -b $t0`
      unset t0

      diff pdbvenv.res $FilesDir/ref/pdbvenv >&! pdbvenv.res.diff
      set dstatus = $status

      if (($xstatus != 0) || ($dstatus != 0)) then
         flog $Log cat pdbvenv.res
         flog $Log cat pdbvenv.res.diff
         set xstatus = 1
      endif

      set rpf = ( $rpf pdbvenv.res pdbvenv.res.diff )

      $TEST_CHECK part -a shell_env -e $xstatus -l -dt $dt -rpf "$rpf" none

      @ nerr = $nerr + $status

# argv test
      NoteD $Log -n "                       argv ......................"
      set rpf = none

      set t0 = `$TIMER -r`
      $CROSS_FE $FilesDir/pdbvexe.scm a 1 2.3 '"abc"' >&! pdbvexe.res
      set xstatus = $status

      set dt = `$TIMER -b $t0`
      unset t0

      diff pdbvexe.res $FilesDir/ref/pdbvexe >&! pdbvexe.res.diff
      set dstatus = $status

      if (($xstatus != 0) || ($dstatus != 0)) then
         flog $Log cat pdbvexe.res
         flog $Log cat pdbvexe.res.diff
         set xstatus = 1
      endif

      set rpf = ( $rpf pdbvexe.res pdbvexe.res.diff )

      $TEST_CHECK part -a shell_argv -e $xstatus -l -dt $dt -rpf "$rpf" none

      @ nerr = $nerr + $status

   endif

$TEST_CHECK part -a shell -e $nerr "$msg"

exit($status)
