#!/bin/csh -f
#
# AXIS - ULTRA AXIS test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/sx/tests/common

set msg = "ULTRA AXIS Test .............."
set exe = $BinDir/ultra
set opt = ( $ulopt -l $FilesDir/ulaxs.scm )
set io  = ulaxs.log

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log $RM ulaxs.log ulaxs.err

   source $PSY_Base/scripts/test-run

   flog $Log ($CROSS_FE $PSDIFF ulaxs.ps $RefDir/ulaxs.ps >&! ulaxs.ps.diff)

   set rpf = ( $rpf ulaxs.* )

$TEST_CHECK part -a fill -e $xstatus -dt $dt -rpf "$rpf" none

exit($status)
