#!/bin/csh -f
#
# ENV - ULTRA environment test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/sx/tests/common

set msg = "ULTRA Env Test ..............."
set exe = $BinDir/ultra
set opt = ( $ulopt -n )
set io  = ulenv.log

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log $RM ulenv.log

   unsetenv SCHEME
   unsetenv ULTRA  
   setenv DO_RUN_SUBMIT_ENV

#   source $PSY_Base/scripts/test-run
   set t0 = `$TIMER -r`
   if ("$Valgrind" == "") then
      flog $Log ($CROSS_FE $exe $opt \(end\) >&! ulenv.log)
      set xstatus = $status
   else
      ftee $Log $Valgrind $exe $opt \(end\)    |& \
      grep "ERROR SUMMARY:"                    |& \
     awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif
   set dt = `$TIMER -b $t0`
   unset t0
   
   set rpf = ( $rpf ulenv.log )

$TEST_CHECK part -a env -e $xstatus -dt $dt -rpf "$rpf" none

exit($status)

