#!/bin/csh -f
#
# FFT - ULTRA FFT test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/sx/tests/common

set msg = "ULTRA FFT Test ..............."
set exe = $BinDir/ultra
set opt = ( $ulopt -l $FilesDir/ulfft.scm )
set io  = ulfft.log

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log $RM ulfft.log ulfft.err

   source $PSY_Base/scripts/test-run

   flog $Log (grep -i "error" ulfft.log >&! ulfft.err)

$TEST_CHECK part -a fft -e $xstatus -dt $dt -rpf "$rpf" none

exit($status)
