#!/bin/csh -f
#
# FILL - ULTRA FILL test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/sx/tests/common

set msg = "ULTRA FILL Test .............."
set exe = $BinDir/ultra
set opt = ( $ulopt -l $FilesDir/ulfill.scm )
set io  = ulfill.log

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log $RM ulfill.log ulfill.err

   source $PSY_Base/scripts/test-run

   flog $Log (grep -i "error" ulfill.log >&! ulfill.err)

$TEST_CHECK part -a fill -e $xstatus -dt $dt -rpf "$rpf" none

exit($status)

