#!/bin/csh -f
#
# MEM - ULTRA memory test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/sx/tests/common

set msg = "ULTRA Memory Test ............"
set exe = $BinDir/ultra
set opt = ( $ulopt -n -l $FilesDir/ulmmt.scm )
set io  = ulmmt.log

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   source $PSY_Base/scripts/test-run

$TEST_CHECK part -a mem -e $xstatus -dt $dt -rpf "$rpf" none

exit($status)
