#!/bin/csh -f
#
# ARRAY - test SCORE dynamic arrays
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE Smart Array Test ........"
set exe = $BinDir/scarts
set opt = ""
set io  = ftee

NoteD $Log ""
NoteD $Log "                    $msg"

flog $Log pushd $SrcDir
flog $Log $MAKE compre
set xstatus = $status
flog $Log popd

if ($xstatus == 0) then
   source ../../../scripts/test-run
endif

$TEST_CHECK part -a array -e $xstatus -dt $dt -x $exe -rpf "$rpf" "$msg"

exit($status)


