#!/bin/csh -f
#
# ARRAY - test SCORE dynamic arrays
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE Smart Array Test ........ "
set exe = $BinDir/scarts

NoteD $LogF ""
NoteD $LogF "                    $msg"

flog $LogF pushd $SrcDir
flog $LogF $MAKE compre
set xstatus = $status
flog $LogF popd

if ($xstatus == 0) then
   if ("$Valgrind" == "") then
      ftee $LogF $CFE $exe
      set xstatus = $status
   else
      ftee $LogF $Valgrind $exe          |& \
      grep "ERROR SUMMARY:"              |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif
endif

$TEST_CHECK part -a array -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)


