#!/bin/csh -f
#
# BUF - test SCORE I/O buffering
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

NoteD $LogF ""
NoteD $LogF "                    SCORE Buffered I/O Test ..... "

set UTime = `$TIMER -r`
flog $LogF pushd $SrcDir
flog $LogF $MAKE io
set xstatus = $status
flog $LogF popd

if ($xstatus == 0) then

   if ("$Valgrind" == "") then
      ftee $LogF $CFE $BinDir/scbfts
      set xstatus = $status
   else
      ftee $LogF $Valgrind scbfts          |& \
      grep "ERROR SUMMARY:"                |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      flog $LogF $RM $Tmp
   endif

   if ($xstatus != 0) then
      set Err = 1
   endif

endif

set ETime   = `$TIMER -b $UTime`

if (($xstatus == 254) || ($xstatus == 255)) then
   NoteD $LogF "                    SCORE Buffered I/O Test ..... OMITTED ($ETime)"
else if ($xstatus != 0) then
   NoteD $LogF "                    SCORE Buffered I/O Test ..... FAILED ($ETime)"
else
   NoteD $LogF "                    SCORE Buffered I/O Test ..... PASSED ($ETime)"
endif

exit($Err)

