#!/bin/csh -f
#
# BUF - test SCORE I/O buffering
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE Buffered I/O Test ....... "
set exe = $BinDir/scbfts

NoteD $Log ""
NoteD $Log "                    $msg"

flog $Log pushd $SrcDir
flog $Log $MAKE io
set xstatus = $status
flog $Log popd

if ($xstatus == 0) then

   if ("$Valgrind" == "") then
      ftee $Log $CFE $exe
      set xstatus = $status
   else
      ftee $Log $Valgrind $exe             |& \
      grep "ERROR SUMMARY:"                |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

endif

$TEST_CHECK part -a buf -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)

