#!/bin/csh -f
#
# ERROR - test SCORE error handling
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE Error Test .............. "
set exe = $BinDir/scerts

   NoteD $LogF ""
   NoteD $LogF -n "                    $msg"
   NoteD $LogF ""

   flog $LogF pushd $SrcDir
   flog $LogF $MAKE error
   set xstatus = $status
   flog $LogF popd

   if ("$Valgrind" == "") then
      ftee $LogF $CFE $exe
      set xstatus = $status
   else
      ftee $LogF $Valgrind $exe       |& \
      grep "ERROR SUMMARY:"           |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

$TEST_CHECK part -a error -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)

