#!/bin/csh -f
#
# IO - test I/O facilities in SCORE
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE I/O Test ................"
set exe = $BinDir/tscio
set opt = ""
set io  = ftee

NoteD $Log ""
NoteD $Log "                    $msg"

flog $Log pushd $SrcDir
flog $Log $MAKE io
set xstatus = $status
flog $Log popd

if ($xstatus == 0) then
   source ../../../scripts/test-run
endif

set rpf = ( $rpf tscio.txt )

$TEST_CHECK part -a io -e $xstatus -dt $dt -x $exe -rpf "$rpf" "$msg"

exit($status)

