#!/bin/csh -f
#
# MMAP - test memory mapped I/O facilities in SCORE
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE Mapped File Test ........ "
set exe = $BinDir/scmfts
set rpf = none

if ($CROSS_COMPILE == FALSE) then

   NoteD $LogF ""
   NoteD $LogF -n "                    $msg"
   NoteD $LogF ""

   flog $LogF pushd $SrcDir
   flog $LogF $MAKE mf
   set xstatus = $status
   flog $LogF popd

   if ($xstatus == 0) then
      if ("$Valgrind" == "") then
         ftee $LogF $CFE $exe
         set xstatus = $status
      else
         ftee $LogF $Valgrind $exe       |& \
         grep "ERROR SUMMARY:"           |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif
   endif

   set rpf = ( $rpf mft.* )

else
   set xstatus = 0
endif

$TEST_CHECK part -a mmap -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)

