#!/bin/csh -f
#
# MMAP - test memory mapped I/O facilities in SCORE
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE Mapped File Test ........ "
set exe = $BinDir/scmfts

if ($CROSS_COMPILE == FALSE) then

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   NoteD $Log ""

   flog $Log pushd $SrcDir
   flog $Log $MAKE mf
   set xstatus = $status
   flog $Log popd

   if ($xstatus == 0) then
      if ("$Valgrind" == "") then
         ftee $Log $CFE $exe
         set xstatus = $status
      else
         ftee $Log $Valgrind $exe        |& \
         grep "ERROR SUMMARY:"           |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif
   endif

   set rpf = ( $rpf mft.* )

endif

$TEST_CHECK part -a mmap -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)

