#!/bin/csh -f
#
# MOR - malloc override test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE Override Test ........... "
set exe = $BinDir/scmots

set ok = TRUE
if (($CROSS_COMPILE == TRUE) || ($PACT_CC_FAMILY == INTEL)) then
   set ok = FALSE
endif

if ($ok == TRUE) then

   NoteD $LogF ""
   NoteD $LogF -n "                    $msg"
   NoteD $LogF ""

   flog $LogF pushd $SrcDir
   flog $LogF $MAKE memovr
   set xstatus = $status
   Note $LogF "make status = $xstatus"

   flog $LogF popd

   if ($xstatus == 0) then
      flog $Log ldd $exe
      if ("$Valgrind" == "") then
#         ftee $LogF ( ( setenv LD_PRELOAD $LibDir/libosmm.so ; $CFE $exe ) |& grep -v "Dwarf Error" |& grep -iwv error )
#         ftee $LogF ( ( setenv LD_PRELOAD $LibDir/libosmm.so ; $CFE $exe ) |& grep -v "Dwarf Error" )
#         ftee $LogF ( setenv LD_PRELOAD $LibDir/libosmm.so ; $CFE $exe )
         ftee $LogF $CFE $exe
         set xstatus = $status
      endif
   else
      Note $LogF "Failed to build scmots - skipping"
      set xstatus = 0
   endif

   $TEST_CHECK part -a mor -e $xstatus -x $exe -rpf "$rpf" "$msg"

   set xstatus = $status

else

   set xstatus = 0

endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

exit($xstatus)

