#!/bin/csh -f
#
# MPRF - test performance of SCORE MM
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE MM Performance Test ..... "
set exe = $BinDir/scmpft
set rpf = none

NoteD $LogF ""
NoteD $LogF "                    $msg"

flog $LogF pushd $SrcDir
flog $LogF $MAKE memchk
set TStatus = $status
flog $LogF popd

if ($TStatus != 0) then
   NoteD $LogF "                         ERROR Building MM Performance Program"
   NoteD $LogF "                    ${mgs}FAILED"
   set Err = 1
else

   if ("$Valgrind" == "") then
      ftee $LogF $CFE $exe -m 1
      set xstatus = $status
   else
      ftee $LogF $Valgrind $exe -m 1      |& \
      grep "ERROR SUMMARY:"               |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

$TEST_CHECK part -a mprf -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)

