#!/bin/csh -f
#
# MPRF - test performance of SCORE MM
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE MM Performance Test ..... "
set exe = $BinDir/scmpft

NoteD $Log ""
NoteD $Log "                    $msg"

flog $Log pushd $SrcDir
flog $Log $MAKE memchk
set xstatus = $status
flog $Log popd

if ($xstatus != 0) then
   NoteD $Log "                         ERROR Building MM Performance Program"
   NoteD $Log "                    ${mgs}FAILED"
else

   set opt = ( -m 1 )
   if ("$Valgrind" == "") then
      ftee $Log $CFE $exe $opt
      set xstatus = $status
   else
      ftee $Log $Valgrind $exe $opt       |& \
      grep "ERROR SUMMARY:"               |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif
endif

$TEST_CHECK part -a mprf -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)

