#!/bin/csh -f
#
# RESRC - test SCORE resource handling
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE Resource Test ..........."
set exe = $BinDir/scrsts
set opt = ""
set io  = ftee

NoteD $Log ""
NoteD $Log -n "                    $msg"
NoteD $Log ""

flog $Log pushd $SrcDir
flog $Log $MAKE resource
set xstatus = $status
flog $Log popd

source ../../../scripts/test-run

$TEST_CHECK part -a resrc -e $xstatus -dt $dt -x $exe -rpf "$rpf" "$msg"

exit($status)

