#!/bin/csh -f
#
# RESRC - test SCORE resource handling
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE Resource Test ........... "
set exe = $BinDir/scrsts

NoteD $Log ""
NoteD $Log -n "                    $msg"
NoteD $Log ""

flog $Log pushd $SrcDir
flog $Log $MAKE resource
set xstatus = $status
flog $Log popd

if ("$Valgrind" == "") then
   ftee $Log $CFE $exe
   set xstatus = $status
else
   ftee $Log $Valgrind $exe          |& \
   grep "ERROR SUMMARY:"             |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
   set rpf     = ( $rpf $Tmp )
endif

$TEST_CHECK part -a resrc -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)

