#!/bin/csh -f
#
# BROWSE - PDB browse test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Browse Test .................... "
set exe = $BinDir/pdlsts
set opt = ( pdatst.db )
set io  = pdatst.lst

NoteD $Log ""
NoteD $Log -n "                    $msg"
Note $Log ""

source ../../../scripts/test-run

# cleanout all previous test files
# no further tests will need them
flog $Log $RM *.db* *.rs*

set rpf = ( $rpf pdatst.lst )

$TEST_CHECK part -a browse -e $xstatus -dt $dt -x $exe -rpf "$rpf" none

exit($status)
