#!/bin/csh -f
#
# BROWSE - PDB browse test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Browse Test .................... "
set rpf = "none"
set exe = $BinDir/pdlsts

set tst = $1

NoteD $LogF ""
NoteD $LogF -n "                    PDB Browse Test .................... "
Note $LogF ""

if ("$Valgrind" == "") then
   $CFE $exe pdatst.db >& pdatst.lst
   set xstatus = $status
else
   ftee $LogF $Valgrind $exe pdatst.db          |& \
   grep "ERROR SUMMARY:"                        |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
   set rpf     = ( $rpf $Tmp )
endif

set rpf = ( $rpf pdatst.lst )

flog $LogF rm *.db? *.rs?

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK part -a browse -e $xstatus -x $exe -rpf "$rpf" none

exit($status)
