#!/bin/csh -f
#
# BUFB - PDB I/O buffer test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Buffer Test B .................."
set exe = $BinDir/tpdb
#set opt = ( -n -v $tst )
set opt = ( -n )

set STRACE = ( `which strace` )

if ("$Valgrind" == "") then

   NoteD $Log ""
   NoteD $Log "                    $msg"
   Note $Log ""

# scan prime number buffer sizes
   @ lerr = 0

   foreach n ( 3 13 127 4093 32749 )
      set fill = `fill-string -n 32 $n`
      flog $Log $CFE $exe $opt -b $n

#   foreach n ( 13 127 4093 32749 )
#      set fill = `fill-string -n 32 $n`
#      flog $Log $CFE $exe -b $n $opt

      set xstatus = $status
      if (($xstatus == 254) || ($xstatus == 255)) then
         NoteD $Log "                        $fill (omitted)"
      else if ($xstatus == 0) then
         NoteD $Log "                        $fill (ok)"
      else
         NoteD $Log "                        $fill (ng)"
         @ lerr = $lerr + 1
      endif
   end

   $TEST_CHECK part -a bufb -e $xstatus -x $exe "$msg"

   set xstatus = $status

endif

exit($xstatus)
