#!/bin/csh -f
#
# CAST - PDB cast test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Recursive Cast Test ............"
set exe = $BinDir/tpdrc
set opt = ( -v $tst foo.pdb )
set io  = ftee

NoteD $Log ""
NoteD $Log -n "                    $msg"
Note $Log ""

source ../../../scripts/test-run

set rpf = ( $rpf foo.pdb )

$TEST_CHECK part -a cast -e $xstatus -dt $dt -x $exe -rpf "$rpf" none

exit($status)
