#!/bin/csh -f
#
# CHECKSUM - PDB checksum test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Checksum Test  ................. "
set exe = $BinDir/pdcsts
set opt = ( -v $tst )
set io  = ftee

NoteD $Log ""
NoteD $Log "                    $msg"
Note $Log ""

source ../../../scripts/test-run

$TEST_CHECK part -a checksum -e $xstatus -x $exe "$msg"

exit($status)

