#!/bin/csh -f
#
# DP - PDB distributed parallel test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Distributed Parallel Test ...... "
set exe = $BinDir/pddpts

if ("$MPI" != "") then
   NoteD $LogF ""
   NoteD $LogF "                    $msg"
   NoteD $LogF ""

   flog $LogF pushd $SrcDir
   flog $LogF $MAKE dp
   set xstatus = $status
   flog $LogF popd

   if ($xstatus != 0) then
      NoteD $LogF ""
      NoteD $LogF "                         ERROR Building Distributed Parallel Tests"
      NoteD $LogF "                    ${msg}FAILED"

   else
      if (-x $PFE) then

         flog $LogF $PFE -dr -p 2 -t 0 $exe -v $tst
         ftee $LogF ( $PFE -p 2 -t 0 $exe -v $tst |& awk '$1 !~ /MPI/ && $1 !~ /ERROR/ && $1 !~ /srun/ {print}' | grep -v filenoexist | grep -v salloc )
         set xstatus = $status

      else
         Note $LogF "No MPI - test omitted"
         set xstatus = 255
      endif

      $TEST_CHECK part -a dp -e $xstatus -x $exe "$msg"

      set xstatus = $status

   endif
endif

exit($xstatus)
