#!/bin/csh -f
#
# FIXDNRM - PDB fix denorm test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Fix Denorm Test ................ "
set exe = $BinDir/pdnrmt

NoteD $Log ""
NoteD $Log -n "                    $msg"
Note $Log ""

set opt = ( -v $tst )
if ("$Valgrind" == "") then
   ftee $Log $CFE $exe $opt
   set xstatus = $status
else
   ftee $Log $Valgrind $exe $opt         |& \
   grep "ERROR SUMMARY:"                 |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
   set rpf     = ( $rpf $Tmp )
endif

$TEST_CHECK part -a fixdnrm -e $xstatus -x $exe -rpf "$rpf" none

exit($status)

