#!/bin/csh -f
#
# FREE - PD_free test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Free Test ...................... "
set rpf = "none"
set exe = $BinDir/pdfrts

set tst = $1

NoteD $LogF ""
NoteD $LogF -n "                    $msg"

if ("$Valgrind" == "") then
   flog $Log $CFE $exe
   set xstatus = $status
else
   ftee $LogF $Valgrind $exe             |& \
   grep "ERROR SUMMARY:"                 |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
   set rpf     = ( $rpf $Tmp )
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK part -a free -e $xstatus -x $exe -rpf "$rpf" none

exit($status)

