#!/bin/csh -f
#
# FREE - PD_free test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set tst = $1

NoteD $LogF ""
NoteD $LogF -n "                    PDB Free Test ...................... "

set UTime = `$TIMER -r`
if ("$Valgrind" == "") then
   flog $Log $CFE $BinDir/pdfrts
   set xstatus = $status
else
   ftee $LogF $Valgrind $BinDir/pdfrts |& \
   grep "ERROR SUMMARY:"                 |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
	 flog $LogF $RM $Tmp
endif
set ETime   = `$TIMER -b $UTime`

unalias grep

if (($xstatus == 254) || ($xstatus == 255)) then
   NoteD $LogF "OMITTED ($xstatus/$ETime)"
else if ($xstatus != 0) then
   NoteD $LogF "FAILED ($xstatus/$ETime)"
   set Err = 1
else
   NoteD $LogF "PASSED ($ETime)"
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK -a free -e $Err part

exit($status)

