#!/bin/csh -f
#
# GATSCA - PDB gather/scatter test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Gather/Scatter Test ............ "
set exe = $BinDir/pdgsts

NoteD $LogF ""
NoteD $LogF "                    $msg"
Note $LogF ""

if ("$Valgrind" == "") then
   ftee $LogF $CFE $exe -v $tst
   set xstatus = $status
else
   ftee $LogF $Valgrind $exe -v $tst |& \
   grep "ERROR SUMMARY:"                      |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
   set rpf     = ( $rpf $Tmp )
endif

$TEST_CHECK part -a gatsca -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)
