#!/bin/csh -f
#
# HYPER - PDB hyperstride test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Hyperstride Test ..............."
set exe = $BinDir/pdopts
set opt = ( -v $tst )
set io  = ftee

NoteD $Log ""
NoteD $Log -n "                    $msg"
Note $Log ""

source ../../../scripts/test-run

$TEST_CHECK part -a hyper -e $xstatus -dt $dt -x $exe -rpf "$rpf" none

exit($status)
