#!/bin/csh -f
#
# MASTER - PDB master test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Master Test .................... "
set exe = $BinDir/pdbtst
set opt = ( -v $tst )
set io  = ftee

NoteD $Log ""
NoteD $Log "                    $msg"
Note $Log ""

source ../../../scripts/test-run

$TEST_CHECK part -a master -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)

