#!/bin/csh -f
#
# TYPDEF - PDB typedef test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

unalias *

source ../../tests/common

set tst = $1

NoteD $LogF ""
NoteD $LogF -n "                    PDB Typedef Test ................... "
Note $LogF ""

set UTime = `$TIMER -r`
if ("$Valgrind" == "") then
   flog $LogF $CFE $BinDir/pdtdts -v $tst
   set xstatus = $status
else
   ftee $LogF $Valgrind $BinDir/pdtdts -v $tst |& \
   grep "ERROR SUMMARY:"                       |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
	 flog $LogF $RM $Tmp
endif
set ETime   = `$TIMER -b $UTime`

if (-f out.pdb) then
   flog $Log ls -l out.pdb
   flog $LogF ( grep -a Float out.pdb | grep -a double )
   if ($status == 0) then
      Note $LogF "Result ok"
   else
      Note $LogF "Result ng"
      flog $LogF set xstatus = 2
   endif
endif

if (($xstatus == 254) || ($xstatus == 255)) then
   NoteD $LogF "OMITTED ($xstatus/$ETime)"
else if ($xstatus != 0) then
   NoteD $LogF "FAILED ($xstatus/$ETime)"
   set Err = 1
else
   NoteD $LogF "PASSED ($ETime)"
   flog $LogF rm -f out.pdb
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK -a typdef -e $Err part

exit($status)
