#!/bin/csh -f
#
# TYPDEF - PDB typedef test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

unalias *

source ../../tests/common

set tst = $1

NoteD $LogF ""
NoteD $LogF -n "                    PDB Typedef Test ................... "

set UTime = `$TIMER -r`
if ("$Valgrind" == "") then
   $CFE $BinDir/pdtdeftst >& pdtdeftst.log
   set xstatus = $status
else
   ftee $LogF $Valgrind $BinDir/pdtdeftst |& \
   grep "ERROR SUMMARY:"                 |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
	 flog $LogF $RM $Tmp
endif
set ETime   = `$TIMER -b $UTime`

if ($xstatus == 0) then
   set check = `tail out.pdb | grep Float | sed -e 's|Float.*double.*|pass|'`
else
   set check = "fail"
endif

if (($xstatus == 254) || ($xstatus == 255)) then
   NoteD $LogF "OMITTED ($xstatus/$ETime)"
else if (($xstatus != 0) || ("$check" != "pass")) then
   NoteD $LogF ">$check<"
   NoteD $LogF "FAILED ($xstatus/$ETime)"
   set Err = 1
else
   NoteD $LogF "PASSED ($ETime)"
   flog $LogF rm -f out.pdb
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK -a typdef -e $Err part

exit($status)
