#!/bin/csh -f
#
# DO-TEST - full PANACEA test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

setenv Package panacea
setenv Test abc
source ../../../scripts/test-env

set PIncDir  = $IncDir
set PBinDir  = $BinDir

set Base     = $cwd
set Base     = $Base:h
set RootDir  = $Base/dev

set RootDir  = $RootDir/$SYS_ID
set BinDir   = $RootDir/bin
set IncDir   = $RootDir/include

if (!(-d $SYS_Prefix)) then
   mkdir $SYS_Prefix
endif

cd $SYS_Prefix

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

   set msg = "   S ..."

   cp ../tsrc1 .
   Note $Log "Running source preprocessor $msg"

   set exe = $BinDir/s
   set rpf = tsrc1
   set opt = tsrc1
   set io  = flog

   source ../../../../scripts/test-run

   $TEST_CHECK part -a abc_s -e $xstatus -dt $dt -x $exe -l -rpf "$rpf" "$msg"

   @ nerr = $nerr + $status

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

   if ($nerr == 0) then

      set msg = "   A ..."

      Note $Log "Running generator code $msg"

      set exe = $BinDir/a
      set rpf = none
      set opt = ../st.g
      set io  = flog

      source ../../../../scripts/test-run

      $TEST_CHECK part -a abc_a -e $xstatus -dt $dt -x $exe -l -rpf "$rpf" "$msg"

      @ nerr = $nerr + $status

   endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

   if ($nerr == 0) then

      set msg = "   B ..."

      Note $Log "Running simulation code $msg"

      set exe = $BinDir/b
      set rpf = none
      set opt = st.r00
      set io  = flog

      source ../../../../scripts/test-run

      $TEST_CHECK part -a abc_b -e $xstatus -dt $dt -x $exe -l -rpf "$rpf" "$msg"

      @ nerr = $nerr + $status

   endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

flog $Log $RM $Tmp

if ($nerr == 0) then
   flog $Log rm st.* test.* tsrc1.*
endif

exit($nerr)

