#!/bin/csh -f
#
# ABC - test simple PANACEA code
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PANACEA ABC Test .............. "

if (-d $RootDir/panacea/abc) then
   NoteD $Log ""
   NoteD $Log -n "                    Building PANACEA ABC Test ....."
   Note $Log ""

   setenv SESSION_CONFIG `cfgman use`
   flog $Log pushd $SrcDir/abc/builder
   flog $Log dsys remove
   flog $Log dsys config
   flog $Log dsys build
   set xstatus = $status
   flog $Log popd

   if ($xstatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         Can't build PANACEA ABC Test"
   else
      NoteD $Log " DONE"

      NoteD $Log ""
      NoteD $Log "                    $msg"

      flog $Log pushd $SrcDir/abc/builder
      if ("$Valgrind" == "") then
         ftee $Log dsys test
         set xstatus = $status
      else
         ftee $Log dsys test -vg
         set xstatus = $status
      endif
      flog $Log popd

      if ($xstatus == 0) then
         flog $Log pushd $SrcDir/abc/builder
         flog $Log dsys remove
         flog $Log popd
      endif
   endif
endif

$TEST_CHECK part -a abc -e $xstatus "$msg"

exit($status)

