#!/bin/csh -f
#
# GEN - test panache
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PANACHE Test .................. "

NoteD $Log ""
NoteD $Log ""
NoteD $Log "                    $msg"

flog $Log pushd $SrcDir/tests
do-test
set xstatus = $status
flog $Log popd

$TEST_CHECK part -a gen -e $xstatus "$msg"

exit($status)

