#!/bin/csh -f
#
# APPDEF - PDB append/defent test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Append/Defent Test ............."
set exe = $BinDir/tpdap
set opt = ( -v $tst )
set io  = ftee

NoteD $Log ""
NoteD $Log "                    $msg"
Note $Log ""

source ../../../scripts/test-run

$TEST_CHECK part -a appdef -e $xstatus -dt $dt -x $exe -rpf "$rpf" "$msg"

exit($status)
