#!/bin/csh -f
#
# BIN - PDBNet binary communication tests
#
# include "cpyright.h"
#

source $PSY_Base/pdb/tests/common

set msg = "PDBNet Binary Test ............."
set exe = $BinDir/tpnb

set DPE = ""

# this test fails too often on DP machines so don't run there

# NOTE: remove this when properly rehosted on PDB Net
if (0) then
      if ("$DPE" != "") then
         NoteD $Log ""
         NoteD $Log -n "                    $msg"
         Note $Log ""

         (echo "hello" ; echo "end") | $CROSS_FE $exe >&! tpnb.res
         set xstatus = $status
         if ($xstatus == 123) then
            set xstatus = 251
         endif
   
         set rpf = ( $rpf tpnb.res )

         $TEST_CHECK part -a bin -e $xstatus -x $exe -rpf "$rpf" "$msg"
      endif
endif

exit($status)
