#!/bin/csh -f
#
# CHK++ - PDB C++ API compile test
#
# include "cpyright.h"
#

unalias *

@ err = 0

source ../../tests/common

if ($TEST_SKIP !~ *pdb:pdb_chk++*) then

   set msg = "PDB C++ API Test ..................."

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   set res = chk++.res

   flog $Log pwhere a++
   flog $Log ( a++ -ag -I$IncDir -c $FilesDir/chk++.cc -o chk++.o >&! $res )
   @ xstatus = `cat $res | wc -l`

   set rpf = ( $rpf chk++.o )

   $TEST_CHECK part -a chk++ -e $xstatus -dt $dt -rpf "$rpf" none
   @ err = $err + $status

endif

exit($err)

