#!/bin/csh -f
#
# COMMON - support for PDB test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

setenv Package  pdb
setenv Test     $0:t
source $PSY_Base/scripts/test-env

set tst = $1

