#!/bin/csh -f
#
# FD - PDB file descriptor leak test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/pdb/tests/common

set msg = "PDB FD Leak ........................"
set exe = $BinDir/tpdfd
set opt = ""
set io  = flog

if ("$OS" != AIX) then

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   source $PSY_Base/scripts/test-run

   $TEST_CHECK part -a fd -e $xstatus -dt $dt -x $exe none

   set xstatus = $status

endif

exit($xstatus)
