#!/bin/csh -f
#
# SMP - PDB SMP parallel test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/pdb/tests/common

set msg = "PDB SMP Parallel Test .............."
set exe = $BinDir/tpdsmp
set opt = ( -v $tst -m 0 )
set io  = flog

if ("$Parallel" != "") then
   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log pushd $SrcDir
   flog $Log $MAKE smp
   set xstatus = $status
   flog $Log popd

   if ($xstatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         ERROR Building SMP Parallel Tests"
      NoteD $Log "                    ${msg}FAILED"
   else
      source $PSY_Base/scripts/test-run
      set rpf = ( $rpf ptest.pdb wrn.pdb )
   endif

   $TEST_CHECK part -a smp -e $xstatus -dt $dt -x $exe -rpf "$rpf" none

   set xstatus = $status

endif

exit($xstatus)

