#!/bin/csh -f
#
# RENDLR - PGS basic LR rendering tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PGS Basic Test ......... "
set rpf = "none"
set exe = $BinDir/gsatst

   NoteD $Log ""
   NoteD $Log -n "                    $msg"

   flog $Log pushd $SrcDir
   flog $Log $MAKE Cstd
   set TStatus = $status
   flog $Log popd

   if ($TStatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         Can't build PGS Basic Test Program"
      NoteD $Log "                    PGS Line Plot Test ..... FAILED"
      set Err = 1
   else

      if ("$Valgrind" == "") then
         ftee $Log $CFE $exe -A -3 -8 -11 -12 -r 500
         set xstatus = $status
      else
         ftee $Log $Valgrind $exe -A -3 -8 -11 -12 -r 500           |& \
         grep "ERROR SUMMARY:"                                      |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif

      if ($xstatus == 0) then
         flog $Log $CFE $PSDIFF gspsts.ps $RefDir/gspsts.ps
         set xstatus = $status
      endif

      flog $Log touch gsjpgt.jpg.foo
      set rpf = ( $rpf gscgmt.cgm gspsts.ps gscgmt.cgm gsjpgt.jpg.* gspngt.png.* )

      NoteD $Log ""
   endif

$TEST_CHECK part -a rendlr -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)
