#!/bin/csh -f
#
# DRIVER - SCC test driver script
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set tst = $1

if ($CROSS_COMPILE == FALSE) then
   set refdir = $SrcDir/tests/ref
   set fill   = `fill-string -n 25 $tst`
#   set opt    = ( -check -mem )
   set opt    = ( -check )

   Separator $Log
   Note $Log ""
   NoteD $Log -n "                    $fill "
   Note $Log ""

   set t0 = `$TIMER -r`
   flog $Log cp $SrcDir/tests/$tst.c .

   scc $opt -c $tst.c >&! $tst.res
   set xstatus = $status
   if ($xstatus != 0) then
      @ nerr = 253
   endif

# for tests with fiducial results
   if (-f $refdir/$tst) then
      flog $Log diff $tst.res $refdir/$tst
      set xstatus = $status
      if ($xstatus != 0) then
         flog $Log @ nerr = 252
         flog $Log cat $tst.res
      endif

# for tests without fiducial results
   else
      flog $Log grep "Memory Map" $tst.res
      set xstatus = $status
      if ($xstatus == 0) then
         @ nerr = 250
      endif
   endif

   set dt = `$TIMER -b $t0`

   $TEST_CHECK part -a scc_$tst -e $nerr -l -dt $dt none

   set xstatus = $status

endif

exit($xstatus)

