#!/bin/csh -f
#
# CONFIGURED - write the CONFIGURED file
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

unalias *

# put these in shell variables since
# prune-env will remove them as environment variables
set Log    = $1
set ScrDir = $2
set lCfg   = $3

eval `$ScrDir/prune-env -e DbgOpt pact`
set path = ( $ScrDir $path )
source $ScrDir/functions-pact.csh

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

Separator $Log
NoteD $Log "   Configuration record - configured"
Note $Log ""

dbmget $Log EtcDir^        \
            UseTmpDir^     \
            FilterDir^     \
            Host^          \
            OS_Name^       \
            HAVE_JPEGLIB^  \
            HAVE_PNGLIB^   \
            WARN_PATTERN^  \
            ERR_PATTERN^   \
            USER

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

    set STDOUT = $EtcDir/configured

    flog $Log $RM $STDOUT
    flog $Log touch $STDOUT

    Note $STDOUT "Config       = $lCfg"
    Note $STDOUT "DbgOpt       = $DbgOpt"
    Note $STDOUT "Date         = `date`"
    if ("$HAVE_JPEGLIB" == "") then
       Note $STDOUT "JPEG         = no"
    else
       Note $STDOUT "JPEG         = yes"
    endif

    if ("$HAVE_PNGLIB" == "") then
       Note $STDOUT "PNG          = no"
    else
       Note $STDOUT "PNG          = yes"
    endif

    if (-f $lCfg) then
       set Shared = `grep Shared $lCfg`
       if ("$Shared" == "") then
          Note $STDOUT "Shared       = no"
       else
          Note $STDOUT "Shared       = yes"
       endif
    endif

    Note $STDOUT "UseTmpDir    = $UseTmpDir"
    Note $STDOUT "FilterDir    = $FilterDir"
    Note $STDOUT "WARN_PATTERN = $WARN_PATTERN"
    Note $STDOUT "ERR_PATTERN  = $ERR_PATTERN"

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

exit(0)

