#!/bin/csh -f
#
# DATTR - ULTRA PDB attribute test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SX PDB Attribute Test ........ "
set exe = $BinDir/sx

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   set opt = ( -l $RootDir/sx/tests/sxpdba.scm )
   if ("$Valgrind" == "") then
      flog $Log ($SX $opt > sxpdba.res)
      set xstatus = $status
      if ($xstatus == 0) then
         flog $Log (diff sxpdba.res $RootDir/sx/tests/ref/sxpdba > sxpdba.res.diff)
         set xstatus = $status
      endif
   else
      ftee $Log $Valgrind $exe -e -r -s $opt     |& \
      grep "ERROR SUMMARY:"                      |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

   set rpf = ( $rpf sxpdba.res sxpdba.res.diff )

$TEST_CHECK part -a dattr -e $xstatus -rpf "$rpf" none

exit($status)
