#!/bin/csh -f
#
# HASH - SX HASH test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SX HASH Test ................. "
set exe = $BinDir/sx
set opt = ( -e -r -s $ZeroSpace -l $FilesDir/sxhash.scm )
set io  = sxhash.res.tmp

   set sys = `uname`

   if (("$sys[1]" != "AIX") && ("$LARGE_FILES" == ""))  then
      NoteD $Log ""
      NoteD $Log -n "                    $msg"
      Note $Log ""

      source ../../../scripts/test-run

      if (($xstatus == 0) && ("$Valgrind" == "")) then
         cat sxhash.res.tmp          | \
         sed -e '/diskaddr =/d'        \
             -e '/size =/d'            \
             -e '/alignment =/d'       \
             -e '/member_offs =/d'     \
             -e '/cast_offs =/d'       \
             -e '/number =/d'          \
             -e '/bpi =/d'             \
             -e '/order/d'             \
             -e '/format/d'            \
             -e 's/ . 0 5 7 6.98/ d 0 5 7 6.98/g'   \
             -e 's/long_long/long/g'   \
             -e 's/#([^A-Za-z)]*)//g' > sxhash.res

         flog $Log (diff -b sxhash.res $FilesDir/ref/sxhash > sxhash.res.diff)
         set xstatus = $status
      endif

      set rpf = ( $rpf sxhash.res.tmp sxhash.res sxhash.res.diff )
   endif

$TEST_CHECK part -a hash -e $xstatus -dt $dt -rpf "$rpf" none

exit($status)
