#!/bin/csh -f
#
# OPER - SX operator tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SX OPER Test ................. "
set exe = $BinDir/sx
set opt = ( -p -e -q $ZeroSpace -l $FilesDir/sxoper.scm )
set io  = sxoper.res

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   if ("$MPI" == "") then
      source ../../../scripts/test-run
      set rpf = ( $rpf sxoper.res arr.dat sxoper*.ps )
   endif

$TEST_CHECK part -a oper -e $xstatus -dt $dt -rpf "$rpf" none

exit($status)
