#!/bin/csh -f
#
# PDB - ULTRA PDB test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SX PDB Test .................. "
set exe = $BinDir/sx
set rpf = 0
@ nerr  = 0

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log cp $TDir/sxpdbg.scm .

   set opt = ( -l $RootDir/sx/tests/sxpdb.scm )
   if ("$Valgrind" == "") then
      flog $Log ($SX $opt > sxpdb.res)
      set xstatus = $status
      if ($xstatus == 0) then
         flog $Log (diff sxpdb.res $RootDir/sx/tests/ref/sxpdb > sxpdb.res.diff)
         set xstatus = $status
      endif
   else
      ftee $Log $Valgrind $exe -e -r -s $opt     |& \
      grep "ERROR SUMMARY:"                      |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

   set rpf = ( $rpf sxpdb.res sxpdb.res.diff )

$TEST_CHECK part -a pdb -e $xstatus -rpf "$rpf" none

exit($status)
