#!/bin/csh -f
#
# SHELL - PDBVIEW shell tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDBView Shell Test ........... "
set exe = $BinDir/sx
@ nerr  = 0

   if (($CROSS_COMPILE == FALSE) && ($HaveIPC == YES)) then
      NoteD $Log ""
      NoteD $Log "                    $msg"

# env test
      NoteD $Log -n "                       env ....................... "
      set rpf = none

      set UTime = `$TIMER -r`
      $CFE $FilesDir/pdbvenv.scm >&! pdbvenv.res
      set xstatus = $status
      diff pdbvenv.res $FilesDir/ref/pdbvenv >&! pdbvenv.res.diff
      set dstatus = $status
      set ETime = `$TIMER -b $UTime`

      if (($xstatus != 0) || ($dstatus != 0)) then
         flog $Log cat pdbvenv.res
         flog $Log cat pdbvenv.res.diff
         set xstatus = 1
      endif

      set rpf = ( $rpf pdbvenv.res pdbvenv.res.diff )

      $TEST_CHECK part -a shell_env -e $xstatus -l -rpf "$rpf" none

      @ nerr = $nerr + $status

# argv test
      NoteD $Log -n "                       argv ...................... "
      set rpf = none

      set UTime = `$TIMER -r`
      $CFE $FilesDir/pdbvexe.scm a 1 2.3 '"abc"' >&! pdbvexe.res
      set xstatus = $status
      diff pdbvexe.res $FilesDir/ref/pdbvexe >&! pdbvexe.res.diff
      set dstatus = $status
      set ETime = `$TIMER -b $UTime`

      if (($xstatus != 0) || ($dstatus != 0)) then
         flog $Log cat pdbvexe.res
         flog $Log cat pdbvexe.res.diff
         set xstatus = 1
      endif

      set rpf = ( $rpf pdbvexe.res pdbvexe.res.diff )

      $TEST_CHECK part -a shell_argv -e $xstatus -l -rpf "$rpf" none

      @ nerr = $nerr + $status

   endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK part -a shell -e $nerr "$msg"

exit($status)
