#!/bin/csh -f
#
# TEXT - SX PDB text test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SX PDB Text Test ............. "
set exe = $BinDir/sx

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   set Ref = $RootDir/sx/tests/ref/sxpdbt

   flog $Log rm -f sxpdbt.log sxpdbt.ttx sxpdbt.a sxpdbt.res

   flog $Log cp $TDir/sxpdbg.scm .

   set opt = ( -l $RootDir/sx/tests/sxpdbt.scm )
   if ("$Valgrind" == "") then
      flog $Log ($PDBView $opt >& sxpdbt.res)
      set xstatus = $status
      if ($xstatus == 0) then
         if (-f $Ref) then
            flog $Log diff sxpdbt.res $Ref
            set xstatus = $status
         else
            flog $Log cp sxpdbt.res $Ref
         endif
      endif
   else
      ftee $Log $Valgrind $exe -e -p -q $opt     |& \
      grep "ERROR SUMMARY:"                      |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

   flog $Log touch sxpdbt.foo
   set rpf = ( $rpf sxpdbt.* )

$TEST_CHECK part -a text -e $xstatus -rpf "$rpf" none

exit($status)
