#!/bin/csh -f
#
# VIF - ULTRA PDB VIF test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SX PDB VIF Test .............. "
set exe = $BinDir/sx
set opt = ( -p -e -q $ZeroSpace -l $FilesDir/sxpdbi.scm )
set io  = sxpdbi.res

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   set sys = `uname -m`

   if (("$sys[1]" != "CRAY") && ("$MPI" == "")) then

      source ../../../scripts/test-run

      if ("$Valgrind" == "") then
         if ($xstatus == 0) then
            flog $Log (diff sxpdbi.res $FilesDir/ref/sxpdbi > sxpdbi.res.diff)
            set xstatus = $status
         else
            flog $Log cp sxpdbi.res sxpdbi.res.crash
         endif
         set rpf = ( $rpf sxpdbi.res sxpdbi.res.diff )
      endif

   else
      set xstatus = 0
   endif

$TEST_CHECK part -a vif -e $xstatus -dt $dt -rpf "$rpf" none

exit($status)
