#!/bin/csh -f
#
# VIF - ULTRA PDB VIF test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SX PDB VIF Test .............. "
set exe = $BinDir/sx

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   set sys = `uname -m`

   if (("$sys[1]" != "CRAY") && ("$MPI" == "")) then

      set opt = ( -l $RootDir/sx/tests/sxpdbi.scm )
      if ("$Valgrind" == "") then
         flog $Log ($PDBView $opt > sxpdbi.res)
         set xstatus = $status
         if ($xstatus == 0) then
            flog $Log (diff sxpdbi.res $RootDir/sx/tests/ref/sxpdbi > sxpdbi.res.diff)
            set xstatus = $status
         else
            flog $Log cp sxpdbi.res sxpdbi.res.crash
         endif
      else
         ftee $Log $Valgrind $exe -e -r -s $opt     |& \
         grep "ERROR SUMMARY:"                      |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif

      set rpf = ( $rpf sxpdbi.res sxpdbi.res.diff )
   else
      set xstatus = 0
   endif

$TEST_CHECK part -a vif -e $xstatus -rpf "$rpf" none

exit($status)
