#!/bin/csh -f
#
# SCCOM - commit sources whether CVS or SVN
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set MngDir = `dirname $0`

set args = ""
set msg  = ""

while ($#argv > 0)
   switch ($1)
      case -m:
           set msg = ( $argv )
           break
           breaksw
      default:
           set args = ( $args $1 )
           breaksw
   endsw
   shift
end


if (-d $MngDir/CVS) then

   cvs commit $args -m "$msg"

else if (-d $MngDir/.svn) then

   svn commit $args -m "$msg"

endif

exit($status)
