#!/bin/csh -f
#
# DO-NET - test do-net
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "DO-NET Test .................... "
set rpf = none

while ($#argv > 0)
   switch ($1)
      case -h:
           echo ""
           echo "Usage: do-net [-h]"
           echo "  h  this help message"
           echo ""
           exit(1);
      default:
           breaksw
   endsw
   shift
end

@ Err = 0

NoteD $Log ""
NoteD $Log -n "                    $msg"
Note $Log ""

set BTime = `$TIMER -r`

# GOTCHA: fill in the place holder
flog $Log pwd
set xstatus = $status

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK part -a do-net -e $xstatus -rpf "$rpf" none

exit($status)


