#!/bin/csh -f
#
# EXT - test aexec
#

@ err = 0

alias pe  'aexec "\!*"'
alias pg  'eval `aexec "\!*"`'

set proc = TRUE
set proc = FALSE
set var  = TRUE

#set echo 
#set verbose

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# processes only

if ($proc == TRUE) then

   echo "--------------------------"
   echo "ls aexec.c foo.h @o+1 @e+2 cat -n @ cat -E"
   pe ls aexec.c foo.h @o+1 @e+2 cat -n @ cat -E
   echo "status = $status"

   echo "--------------------------"
   echo "ls aexec.c foo.h @o2 @e3 cat -n @ cat -E"
   pe ls aexec.c foo.h @o2 @e3 cat -n @ cat -E
   echo "status = $status"

   echo "--------------------------"
   echo "ls aexec.c foo.h @o2 @e2 cat -n"
   pe ls aexec.c foo.h @o2 @e2 cat -n
   echo "status = $status"

   echo "--------------------------"
   echo "ls aexec.c foo.h @b2 cat -n"
   pe ls aexec.c foo.h @b2 cat -n
   echo "status = $status"
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# VARIABLES - test redirections with variables
#           - the -v <var> MUST come first and mode last

if ($var == TRUE) then

   echo "--------------------------"
   unsetenv foo
   echo "command: date @o2 aexec -v foo -r"
   pg date @o2 aexec -v foo -r
   echo "> foo     = `printenv foo`"
   echo "> xstatus = $xstatus"

   echo "--------------------------"
   echo "command: cat @i2 aexec -v foo -w"
   pe cat @i2 aexec -v foo -w

#   echo "--------------------------"
#   echo "command: date @o2 aexec -v foo -rw"
#   pe date @o2 aexec -v foo -rw
#   echo "> foo     = $foo"
#   echo "> xstatus = $xstatus"

   echo "--------------------------"
   echo "command: date @b2 aexec -v foo -r"
   pe date @b2 aexec -v foo -r
#   echo "> foo     = $foo"
#   echo "> xstatus = $xstatus"

   echo "--------------------------"
   unsetenv foo
   echo "command: date @o2 @e3 aexec -v foo -r @ aexec -v bar -r"
   pg date @o2 @e3 aexec -v foo -r @ aexec -v bar -r
   echo "> foo     = `printenv foo`"
   echo "> bar     = `printenv bar`"
   echo "> xstatus = $xstatus"
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

exit($err)
