#!/bin/csh -f
#
# EXT - test gexec
#

source ../../tests/common

set msg = "GEXEC Test ....................."

set GEXEC = gexec
set PERDB = perdb

set lst = ( job pipe fnc file var )

while ($#argv > 0)
   switch ($1)
      case -h:
           echo ""
           echo "Usage: gexec [-h]"
           echo "  h  this help message"
           echo ""
           exit(1);
      default:
           breaksw
   endsw
   shift
end

   NoteD $Log ""
   NoteD $Log "                    $msg"

   @ nerr = 0

   set tf = `timer -r`

   flog $Log setenv PERDB_PATH $cwd/ext
   flog $Log $PERDB -l -c -s

   flog $Log rm -f ext-*
   flog $Log cp $SrcDir/tests/ext-* .

   Note $Log "Using $GEXEC"
   Note $Log "Path = $PATH"

   flog $Log pwd
   flog $Log ls -l ext-*

   foreach t ($lst)
      Separator $Log

      set f = ( `fill-string -n 28 $t` )
      NoteD $Log -n "                        $f"
      Note $Log ""

      set exe = $t
      set opt = ""
      set rpf = ""

      set lt = `timer -r`

      rm -f ext-*.res.raw >& /dev/null

      dbset gstatus ""

      flog $Log ./ext-$t
      set xstatus = $status

      set lt = `timer -b $lt`

      set rpf = ( $rpf ext-$t )

      $TEST_CHECK part -a gexec_${t} -e $xstatus -dt $lt -x $exe -l -rpf "$rpf" none
      @ nerr = $nerr + $status
   end

   flog $Log $PERDB -l quit:

   set tf = `timer -b $tf`

$TEST_CHECK part -a gexec -e $nerr -dt $tf -rpf "$rpf" "$msg"

exit($status)

