#!/bin/csh -f
#
# EXT-PIPE - test aexec with old shell pipe syntax
#

@ err = 0

source $TestScrDir/env-csh

alias pe  'unsetenv astatus ; echo "" ; echo "Command: \!*" ; aexec \!* ; dbget astatus'

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

echo "------------------------------------------------------------------------"
echo ""
echo "# simple stdout variants"

   pe /bin/echo foo '|' cat -n >&! ext-s1.res
   cat ext-s1.res
   echo "> astatus = $astatus"
   if ("$astatus" != "0 0") then
      @ err = $err + 1
      echo "s1 failed"
   else
      rm -f ext-s1.res
      echo "s1 passed"
   endif

echo ""
echo "------------------------------------------------------------------------"
echo ""
echo "# simsle bonded stdout/stderr variants"

   pe ls ext-* foo.h '|' cat -n >&! ext-s2.res
   cat ext-s2.res
   echo "> astatus = $astatus"
   if ("$astatus" != "2 0") then
      @ err = $err + 1
      echo "s2 failed"
   else
      rm -f ext-s2.res
      echo "s2 passed"
   endif

   pe ls ext-* foo.h '|&' cat -n >&! ext-s3.res
   cat ext-s3.res
   echo "> astatus = $astatus"
   if ("$astatus" != "2 0") then
      @ err = $err + 1
      echo "s3 failed"
   else
      rm -f ext-s3.res
      echo "s3 passed"
   endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

echo ""

exit($err)
