#!/bin/csh -f
#
# EXT-VAR - test aexec with variables
#

@ err = 0

alias pe  'echo "" ; echo "Command: \!*" ; aexec "\!*"'
alias pg  'echo "" ; echo "Command: \!*" ; eval `aexec "\!*"`'

#set echo 
#set verbose

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

echo "------------------------------------------------------------------------"
echo ""
echo "# simple stdout variants"

   unsetenv foo
   pg date @o vw:foo
   echo "> foo     = `printenv foo`"
   echo "> xstatus = $xstatus"
   echo "status = $status"

echo "------------------------------------------------------------------------"
echo ""
echo "# simple stdin variants"

   pe cat @i vr:foo
   echo "status = $status"

echo "------------------------------------------------------------------------"
echo ""
echo "# simple append variants"

   pe date @o2 va:foo
   echo "> foo     = `printenv foo`"
   echo "> xstatus = $xstatus"

echo "------------------------------------------------------------------------"
echo ""
echo "# simple bonded variants"

   pe date @b2 vw:foo
   echo "> foo     = `printenv foo`"
   echo "> xstatus = $xstatus"
   echo "status = $status"

echo "------------------------------------------------------------------------"
echo ""
echo "# non-simple stdout variants"

   unsetenv foo
   pg date @o2 @e3 vw:foo @ vw:bar
   echo "> foo     = `printenv foo`"
   echo "> bar     = `printenv bar`"
   echo "> xstatus = $xstatus"
   echo "status = $status"

   unsetenv foo
   pg ls ext-* foo.h @o2 @e3 vw:foo @ vw:bar
   echo "> foo     = `printenv foo`"
   echo "> bar     = `printenv bar`"
   echo "> xstatus = $xstatus"
   echo "status = $status"

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

echo ""

exit($err)
