#!/bin/csh -f
#
# EXT-FNC - test aexec with functions
#

unalias *

@ err = 0

source $TestScrDir/env-csh

alias pe  'unsetenv astatus ; echo "" ; echo "Command: \!*" ; aexec \!* ; dbget astatus'

rm -f ext-*.res.raw >& /dev/null

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

echo "------------------------------------------------------------------------"
echo ""
echo "# simple stdout variants"

   rm -rf p1out
   pe /bin/echo p1 @o pw:test p1out >&! ext-p1.res
   cat ext-p1.res
   echo "> astatus = $astatus"
   if ("$astatus" != "0 0") then
      @ err = $err + 1
      echo "p1 failed"
   else
      rm -f ext-p1.res
      echo "p1 passed"
   endif

echo "------------------------------------------------------------------------"
echo ""
echo "# simple stdin variants"

   pe cat @i pr:test p1out >&! ext-p2.res
   cat ext-p2.res
   echo "> astatus = $astatus"
   if ("$astatus" != "0 0") then
      @ err = $err + 1
      echo "p2 failed"
   else
      rm -f ext-p2.res
      echo "p2 passed"
   endif

echo "------------------------------------------------------------------------"
echo ""
echo "# simple append variants"

   pe /bin/echo p3 @o2 pa:test p3out >&! ext-p3.res
   cat ext-p3.res
   echo "> astatus = $astatus"
   if ("$astatus" != "0 0") then
      @ err = $err + 1
      echo "p3 failed"
   else
      rm -f ext-p3.res
      echo "p3 passed"
   endif

echo "------------------------------------------------------------------------"
echo ""
echo "# simple bonded variants"

   pe /bin/echo p4 @b2 pw:test p4out >&! ext-p4.res
   cat ext-p4.res
   echo "> astatus = $astatus"
   if ("$astatus" != "0 0") then
      @ err = $err + 1
      echo "p4 failed"
   else
      rm -f ext-p4.res
      echo "p4 passed"
   endif

echo "------------------------------------------------------------------------"
echo ""
echo "# non-simple stdout variants"

   rm -rf p5out
   pe /bin/echo p5 @o2 @e3 pw:test p5out @ pw:test p5err >&! ext-p5.res
   cat ext-p5.res
   echo "> astatus = $astatus"
   if ("$astatus" != "0 0 0") then
      @ err = $err + 1
      echo "p5 failed"
   else
      rm -f ext-p5.res
      echo "p5 passed"
   endif

   rm -rf p6out
   pe ls ext-* foo.h @o2 @e3 pw:test p6out @ pw:test p6err >&! ext-p6.res
   sort ext-p6.res.raw >&! ext-p6.res
   cat ext-p6.res
   echo "> astatus = $astatus"
   if ("$astatus" != "2 0 0") then
      @ err = $err + 1
      echo "p6 failed"
   else
      rm -f ext-p6.res
      echo "p6 passed"
   endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

echo ""

exit($err)
