#!/bin/csh -f
#
# FOR-SYS - apply operation to the code system parts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set STDOUT   = ""

set Directories = ( global lag misc source main )

set cmd = ""
while ($#argv > 0)
   switch ($1)
      case -l:
           shift
           set STDOUT = $1
           breaksw
      default:
           set cmd = ( $cmd $1 )
           breaksw
   endsw
   shift
end

cd ..
foreach Dir ($Directories)
   cd $Dir
   if ("$STDOUT" != "") then
      echo "Doing $cmd in directory $Dir" | tee -ai $STDOUT
      eval $cmd | tee -a $STDOUT
   else
      echo "Doing $cmd in directory $Dir"
      eval $cmd
   endif
   cd ..
end

exit($status)
