#!/bin/csh -f
#
# COMMON - support for PPC test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

setenv Package  ppc
setenv Test     $0:t
source ../../../scripts/test-env

set TEST = "cat $SrcDir/DISCLAIMER"

