#!/bin/csh -f
#
# NUMER - SCHEME numeric tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/scheme/tests/common

set msg = "SCHEME Numeric Test .........."
set exe = $BinDir/scheme
set io  = flog

NoteD $Log ""
NoteD $Log "                    $msg"

flog $Log pwd

#--------------------------------------------------------------------------

#                          INTEGER SYNTAX TESTS

#--------------------------------------------------------------------------

   NoteD $Log -n "                       integer syntax ............"
   Note $Log ""
   set rpf = none
   set opt = ( $shopt -l $FilesDir/shsint.scm )

# test that the SCHEME variable can be derived from the executable path
   flog $Log unsetenv SCHEME
   flog $Log unsetenv DO_RUN_SUBMIT_ENV

   source $PSY_Base/scripts/test-run

   set rpf = ( $rpf '#tmp#' )

   $TEST_CHECK part -a numer_int -e $xstatus -l -dt $dt -rpf "$rpf" none

   @ nerr = $nerr + $status

#--------------------------------------------------------------------------

#                           NUMERIC TESTS

#--------------------------------------------------------------------------

   NoteD $Log -n "                       numeric ..................."
   Note $Log ""
   set rpf = none
   set opt = ( $shopt -l $FilesDir/shnum.scm )

   source $PSY_Base/scripts/test-run

   set rpf = ( $rpf '#tmp#' )

   $TEST_CHECK part -a numer_num -e $xstatus -l -dt $dt -rpf "$rpf" none

   @ nerr = $nerr + $status

#--------------------------------------------------------------------------

#                           COMPLEX NUMERIC TESTS

#--------------------------------------------------------------------------

   NoteD $Log -n "                       complex ..................."
   Note $Log ""
   set rpf = none
   set opt = ( $shopt -l $FilesDir/shcpx.scm )

   source $PSY_Base/scripts/test-run

   set rpf = ( $rpf '#tmp#' )

   $TEST_CHECK part -a numer_complex -e $xstatus -l -dt $dt -rpf "$rpf" none

   @ nerr = $nerr + $status

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK part -a numer -e $nerr "$msg"

exit($status)
