#!/bin/csh -f
#
# SHELL - SCHEME shell tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/scheme/tests/common

set msg = "SCHEME Shell Test ............"
set exe = $BinDir/scheme

   if (($CROSS_COMPILE == FALSE) && ($HaveIPC == YES)) then
      NoteD $Log ""
      NoteD $Log "                    $msg"

# env test
      NoteD $Log -n "                       env ......................."

      set t0 = `$TIMER -r`

      $CROSS_FE $FilesDir/shenv.scm | sed "s|$SrcDir||" >&! shenv.res
      set xstatus = $status
      diff shenv.res $FilesDir/ref/shenv >&! shenv.res.diff
      set dstatus = $status

      set dt = `$TIMER -b $t0`
      unset t0

      if (($xstatus != 0) || ($dstatus != 0)) then
         flog $Log cat shenv.res
         flog $Log cat shenv.res.diff
         set xstatus = 1
      endif

      set rpf = ( shenv.res* )

      $TEST_CHECK part -a shell_env -e $xstatus -l -dt $dt -rpf "$rpf" none

      @ nerr = $nerr + $status

# argv test
      NoteD $Log -n "                       argv ......................"

      set t0 = `$TIMER -r`

      $CROSS_FE $FilesDir/shexe.scm a 1 2.3 '"abc"' >&! shexe.res
      set xstatus = $status
      diff shexe.res $FilesDir/ref/shexe >&! shexe.res.diff
      set dstatus = $status

      set dt = `$TIMER -b $t0`
      unset t0

      if (($xstatus != 0) || ($dstatus != 0)) then
         flog $Log cat shexe.res
         flog $Log cat shexe.res.diff
         set xstatus = 1
      endif

      set rpf = ( shexe.res* )

      $TEST_CHECK part -a shell_argv -e $xstatus -l -dt $dt -rpf "$rpf" none

      @ nerr = $nerr + $status

   endif

$TEST_CHECK part -a shell -e $nerr "$msg"

exit($status)
