#!/bin/csh -f
#
# PSTEST - test PSH
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Package = psh
source ../scripts/test-env

set Tests = ""

while ($#argv > 0)
   switch ($1)
      case -h:
           echo ""
           echo "Usage: pstest [-h] [<test>*]"
           echo "  h  this help message"
           echo ""
           echo "Tests: elide blang regx pco do-net dorun verify"
           echo ""
           exit(1);
      default:
           set Tests = ( $1 )
           breaksw
   endsw
   shift
end

flog $Log pact install

cd $TestDir

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# omit tests - usually in difficult CROSS_COMPILE situation

if ($RUN_TESTS == FALSE) then
   NoteD $Log ""
   NoteD $Log "PSH TESTS ... omitted"

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# run the tests

   else
      NoteD $Log ""
      NoteD $Log "PSH TEST ..."

      if ("$Valgrind" != "") then
         setenv Valgrind  "$Valgrind --suppressions=$RootDir/score/tests/vg.suppress"
      endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

      if ("$Tests" == "") then
         set Tests = ""
      set Tests = ($Tests do-net elide blang regx pco pcsh perdb dorun verify)
      endif

   foreach i ($Tests)
      $SrcDir/tests/$i
      if ($status == 1) then
            set ERROR = TRUE
         endif
   end
   
#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# CLEAN UP - we are all done now
   
   $TEST_CHECK -n PSH -e $ERROR clean

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

endif

$TEST_CHECK -e $ERROR fin

exit($status)

