#!/bin/csh -f
#
# COMMON - support for FORTRAN test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../../scripts/env-csh

if ($?LogF == 0) then
   set TestName = "$0:t"

   InitLog LogF $cwd/log.$TestName.$LogSfx
   pushd ../../../manager >& /dev/null
   set Arch = `cfgman use`
   cd ../dev/$Arch >& /dev/null
   set Root = $cwd
   popd >& /dev/null

   set OS       = `uname -s`
   set BinDir   = $Root/bin
   set LibDir   = $Root/lib
   set MAKE     = $BinDir/pact
   set TIMER    = $BinDir/timer
   set CFE      = $BinDir/do-run
   set PFE      = $BinDir/do-run
   set TEST_MPI = YES
   set MPI      = `pact +l -info HAVE_MPI`
endif

set TDir   = $RootDir/fortran/tests
set RefDir = $TDir/ref

Note $LogF "TDir     = |$TDir|"
Note $LogF "RefDir   = |$RefDir|"
Note $LogF "BinDir   = |$BinDir|"
Note $LogF "CFE      = |$CFE|"
Note $LogF "TEST_MPI = |$TEST_MPI|"
Note $LogF "MPI      = |$MPI|"

if ($?SrcDir == 0) then
   pushd ../.. >& /dev/null
   set SrcDir = $cwd
   popd >& /dev/null
endif

if ($?Log == 1) then
   Note $Log "Log file: $LogF"
endif

set Err = 0

