#!/bin/csh -f
#
# PANACEA - PANACEA API tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common


set msg = "PANACEA API Test ..................."
set exe = $BinDir/pathts

NoteD $LogF ""
NoteD $LogF "                    $msg"

flog $LogF pushd $SrcDir
flog $LogF $MAKE panacea
set xstatus = $status
flog $LogF popd

if ($xstatus != 0) then
   NoteD $LogF ""
   NoteD $LogF "                         Can't build PANACEA API Tests ($xstatus)"

else
   if ("$Valgrind" == "") then
      ftee $LogF $CFE $exe -c 2
      set xstatus = $status
   else
      ftee $LogF $Valgrind $exe -c 2   |&  \
      grep "ERROR SUMMARY:"                      |&  \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = $Tmp
   endif
endif

$TEST_CHECK part -a panacea -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)
