#!/bin/csh -f
#
# PDB - Fortran test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB API Test ....................... "

@ err = 0

set tst = $1

# check for Fortran compiler before doing Fortran test
set FC = `awk '$1 == "FCompiler" { print $3 }' $IncDir/make-def`
if ("$FC" != "") then
   Note $LogF "Using fortran compiler $FC"
   flog $LogF swhich -1 $FC
   flog $LogF set LStat = $status
else
   fog $LogF set LStat = 1
endif

#if (($LStat == 0) && ("$MPI" == "")) then
if ($LStat == 0) then
   NoteD $LogF ""
   NoteD $LogF "                    $msg"

   set FAIL = "NO"

   set UTime = `$TIMER -r`

   flog $LogF pushd $SrcDir
   flog $LogF $MAKE +na 2 pdb
   set TStatus = $status
   flog $LogF popd

   if ($TStatus != 0) then
      NoteD $LogF ""
      NoteD $LogF "                         Cannot build PDB FORTRAN Test Program"
      flog $LogF rm -f $BinDir/pdftst
      flog $LogF rm -f $BinDir/pdfgts
      flog $LogF rm -f $BinDir/pdfhyts
   else

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# test hand written wrappers
      NoteD $LogF -n "                        manual ......................... "
      Note $LogF ""

      set exe = $BinDir/pdftst
      set rpf = ""

      if ("$Valgrind" == "") then
         flog $LogF ( $CFE $exe -p |& cat )
         set xstatus = $status
      else
         Note $LogF ""
         ftee $LogF $Valgrind $exe           |& \
         grep "ERROR SUMMARY:"               |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif

      if ("$rpf" == "") then
         set rpf = none
      endif

      $TEST_CHECK part -a pdb_manual -e $xstatus -x $exe -l -rpf "$rpf" none

      @ err = $err + $status

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# test automatically generated wrappers
      NoteD $LogF -n "                        auto ........................... "
      Note $LogF ""

      set exe = $BinDir/pdfgts
      set rpf = ""

      if ("$Valgrind" == "") then
         flog $LogF ( $CFE $exe -p |& cat )
         set xstatus = $status
      else
         Note $LogF ""
         ftee $LogF $Valgrind $exe           |& \
         grep "ERROR SUMMARY:"               |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif

      if ("$rpf" == "") then
         set rpf = none
      endif

      $TEST_CHECK part -a pdb_auto -e $xstatus -x $exe -l -rpf "$rpf" none

      @ err = $err + $status

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# hyperstride test
      NoteD $LogF -n "                        hyperstride .................... "
      Note $LogF ""

      set exe = $BinDir/pdfhyts
      set rpf = ""

      if ("$Valgrind" == "") then
         flog $LogF $CFE $exe
         set xstatus = $status
      else
         Note $LogF ""
         ftee $LogF $Valgrind $exe            |& \
         grep "ERROR SUMMARY:"                |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif

      if ("$rpf" == "") then
         set rpf = none
      endif

      $TEST_CHECK part -a pdb_hyper -e $xstatus -x $exe -l -rpf "$rpf" none

      @ err = $err + $status

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# distribute parallel test
      if ($MPI == HAVE_MPI) then
         flog $LogF pushd $SrcDir
         flog $LogF $MAKE +na 2 fdp
         set TStatus = $status
         flog $LogF popd

         set CFE = $BinDir/do-run

         NoteD $LogF -n "                        dp ............................. "
         Note $LogF ""

         set exe = $BinDir/pdfdpt
         set rpf = ""

         if ("$Valgrind" == "") then
            flog $LogF $CFE -p 4 $exe
            set xstatus = $status
         else
            Note $LogF ""
            ftee $LogF $Valgrind $exe            |& \
            grep "ERROR SUMMARY:"                |& \
            awk '{ print $4 }'   >&! $Tmp
            set xstatus = `cat $Tmp`
            set rpf     = ( $rpf $Tmp )
         endif

         if ("$rpf" == "") then
            set rpf = none
         endif

         $TEST_CHECK part -a pdb_dp -e $xstatus -x $exe -l -rpf "$rpf" none

         @ err = $err + $status
      endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

endif

$TEST_CHECK part -a pdb -e $err "$msg"

exit($status)
