#!/bin/csh -f
#
# PGS - Fortran test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PGS API Test ....................... "

@ err = 0

set tst = $1

# check for Fortran compiler before doing Fortran test
set FC = `awk '$1 == "FCompiler" { print $3 }' $IncDir/make-def`
if ("$FC" != "") then
   Note $LogF "Using fortran compiler $FC"
   flog $LogF swhich -1 $FC
   flog $LogF set LStat = $status
else
   fog $LogF set LStat = 1
endif

#if (($LStat == 0) && ("$MPI" == "")) then
if ($LStat == 0) then
   NoteD $LogF ""
   NoteD $LogF "                    $msg"

   set FAIL = "NO"

   set UTime = `$TIMER -r`

   flog $LogF pushd $SrcDir
   flog $LogF $MAKE +na 2 pgs
   set TStatus = $status
   flog $LogF popd

   if ($TStatus != 0) then
      NoteD $LogF ""
      NoteD $LogF "                         Cannot build PGS FORTRAN Test Program"
      flog $LogF rm -f $BinDir/pdftst
      flog $LogF rm -f $BinDir/pdfgts
      flog $LogF rm -f $BinDir/pdfhyts
   else

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# test hand written wrappers
      NoteD $LogF -n "                        manual ......................... "
      Note $LogF ""

      set exe = $BinDir/gsftst
      set rpf = ""

      if ("$Valgrind" == "") then
         flog $LogF $CFE $exe -s
         set xstatus = $status
      else
         Note $LogF ""
         ftee $LogF $Valgrind $exe           |& \
         grep "ERROR SUMMARY:"               |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif

      if ("$rpf" == "") then
         set rpf = none
      endif

      $TEST_CHECK part -a pgs_manual -e $xstatus -x $exe -l -rpf "$rpf" none

      @ err = $err + $status

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# test generated wrappers
      NoteD $LogF -n "                        auto ........................... "
      Note $LogF ""

      set exe = $BinDir/gsfgts
      set rpf = ""

      if ("$Valgrind" == "") then
         flog $LogF $CFE $exe -s
         set xstatus = $status
      else
         Note $LogF ""
         ftee $LogF $Valgrind $exe           |& \
         grep "ERROR SUMMARY:"               |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif

      if ("$rpf" == "") then
         set rpf = none
      endif

      $TEST_CHECK part -a pgs_auto -e $xstatus -x $exe -l -rpf "$rpf" none

      @ err = $err + $status

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# contour test
      NoteD $LogF -n "                        contour ........................ "
      Note $LogF ""

      set exe = $BinDir/gsfcts
      set rpf = ""

      if ("$Valgrind" == "") then
         flog $LogF $CFE $exe -s
         set xstatus = $status
      else
         Note $LogF ""
         ftee $LogF $Valgrind $exe -s           |& \
         grep "ERROR SUMMARY:"                  |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif

      if ("$rpf" == "") then
         set rpf = none
      endif

      $TEST_CHECK part -a pgs_contour -e $xstatus -x $exe -l -rpf "$rpf" none

      @ err = $err + $status

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

endif

$TEST_CHECK part -a pgs -e $err "$msg"

exit($status)
