#!/bin/csh -f
#
# GSTEST - test PGS
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

setenv Package pgs
setenv Test    ""
set vgdirs = ( . score )

set ldir   = `dirname $0`
set ldir   = `cd $ldir && pwd`       # ensure absolute path
setenv PSY_Base `dirname $ldir`
source $PSY_Base/scripts/test-env
unset ldir

set Tests = ""

while ($#argv > 0)
   switch ($1)
      case -h:
           echo "Usage: gstest [-h] [-vg] [<test>]*"
           echo "  h       this help message"
           echo "  vg      run tests under valgrind"
           echo "  <test>  one of: rendlr rendac"
           echo "                  grot axis mpeg smp"
           echo ""
           exit(1)
      case -*:
           if ("$Tests" != "") then
              break
           endif
           breaksw
      default:
           set Tests = ( $Tests $1 )
           breaksw
   endsw
   shift
end

cd $TestDir

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# omit tests - usually in difficult CROSS_COMPILE situation

if ($RUN_TESTS == FALSE) then
   NoteD $Log ""
   NoteD $Log "PGS TESTS ... omitted"

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# run the tests

else if (-e $SrcDir/pgs.h) then

   NoteD $Log ""
   NoteD $Log "PGS TEST ..."

   if ("$Tests" == "") then
      set Tests = ""
      set Tests = ( $Tests trans axis rendlr rendac grot mpeg smp )
   endif

   foreach i ($Tests)
      $SrcDir/tests/$i $argv
      @ nerr = $nerr + $status
   end

   $TEST_CHECK clean -n PGS -e $nerr -raf "$Tmp"

   set xstatus = $status

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

endif

$TEST_CHECK fin -e $xstatus

exit($status)

