#!/bin/csh -f
#
# PYTEST - test PYTHON
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

setenv Package python
setenv Test    ""
set vgdirs = ( . )
source ../scripts/test-env

set Tests = ""

while ($#argv > 0)
   switch ($1)
      case -h:
           echo "Usage: pytest [-h] [-vg] [<test>]*"
           echo "  h       this help message"
           echo "  vg      run tests under valgrind"
           echo "  <test>  one of: basic unit"
           echo ""
           exit(1)
      case -*:
           breaksw
      default:
           set Tests = ( $Tests $1 )
           breaksw
   endsw
   shift
end

cd $TestDir

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# omit tests - usually in difficult CROSS_COMPILE situation

if ($RUN_TESTS == FALSE) then
   NoteD $Log ""
   NoteD $Log "PYTHON TESTS ... omitted"

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# run the tests

else if (-f $LPYTHON/pact_2/pdb.py) then

# clean up the test dir
   rm -f $Log
   touch $Log

   NoteD $Log ""
   NoteD $Log "PYTHON TEST ......"

   Note $Log "BinDir     = $BinDir"
   Note $Log "path       = $path"
   Note $Log "MAKE       = $MAKE"
   Note $Log "SrcDir     = $SrcDir"
   Note $Log "PYTHONPATH = $PYTHONPATH"
   Note $Log "python     = $PYTHON"
      
   Note $Log "PYVER       = |$PYVER|"
   Note $Log "PYTHONBIN   = |$PYTHONBIN|"
   Note $Log "LPYTHON     = |$LPYTHON|"
   Note $Log "PYTHON      = |$PYTHON|"
   Note $Log "PACT_Exe    = |$PACT_Exe|"
   Note $Log "Parallel    = |$Parallel|"
   Note $Log "MPI         = |$MPI|"
   flog $Log ../../../manager/pwhich pact
   flog $Log ../../../manager/pwhich cc

   if ("$Tests" == "") then
      set Tests = ""
      set Tests = ( $Tests basic unit )
   endif

   foreach i ($Tests)
      $SrcDir/tests/$i
      @ nerr = $nerr + $status
   end

   $TEST_CHECK clean -n PYTHON -e $nerr -raf "../testfile"

   set xstatus = $status

endif

$TEST_CHECK fin -e $xstatus

exit($status)

