#!/bin/csh -f
#
# GRAPHICS - manage detected graphics
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/common

Note $ALog "Analyze: system graphics"

NoteD $ALog "   System Graphics:"

source $AnaDir/quickdraw
source $AnaDir/opengl
source $AnaDir/x11

source $AnaDir/png
source $AnaDir/jpeg

Separator $ALog

dbmget $ALog CC_Exe^       \
             MDG_Inc^      \
             MDG_Lib^      \
             MDG_Pck^      \
             RPATH

Note $Log "Graphics summary variables:"
Note $Log "   RPATH   = $RPATH"
Note $Log "   MDG_Inc = $MDG_Inc"
Note $Log "   MDG_Lib = $MDG_Lib"
Note $Log "   MDG_Pck = $MDG_Pck"

Separator $Log

exit(0)

