#!/bin/csh -f
#
# INLINE - analyze inline for C compiler
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#


set Me = $0
source $Me:h/common

cat << EOF >! $Tmp.c
inline int b(int y)
   {int x;
    x = y % 2;
    return(x);}
int main(int c, char **v)
   {int x, y;
    y = 8;
    x = b(y);
    return(0);}
EOF

flog $ALog $Cfe_CC_Exe $Cfe_CC_Flags $Tmp.c -o $Tmp
if ($status == 0) then
   setenv HaveINLINE TRUE
   NoteD $ALog "      has inline support"
else
   setenv HaveINLINE FALSE
   NoteD $ALog "      no inline support"
endif

rm -f $Tmp $Tmp.c $Tmp.o

# export the result
SetParent HaveINLINE

#exit(0)
