#!/bin/csh -f
#
# MATH - analyze math library options
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/common

Note $ALog "Analyze: math"

dbmget $ALog HSY_RootInc^            \
             GSL_Path    =\? ""^     \
             BLAS_Path   =\? ""^     \
             LAPACK_Path =\? ""

set MathLib = ""

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# look for GNU Scientific library

if (-d $HSY_RootInc/gsl) then
   set rinc = $HSY_RootInc
   set root = $rinc:h
   flog $ALog setenv GSL_Path $root
   set MathLib = ( $MathLib gsl )
else
   flog $ALog setenv GSL_Path ""
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# look for BLAS

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# look for LAPACK

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

foreach i ("linpack" "slatec" "imsl")
   fexec $ALog man $i @b grep -i "no\ ma"
   if (($gstatus[1] == 0) || ($gstatus[2] == 0)) then
      set MathLib = ($MathLib $i)
   endif
end

if ("$MathLib" != "") then
   NoteD $ALog "      math packages: $MathLib"
endif

dbmset $ALog GSL_Path    = $GSL_Path^       \
             BLAS_Path   = $BLAS_Path^      \
             LAPACK_Path = $LAPACK_Path

exit(0)

