#!/bin/csh -f
#
# OSX-EVOLUTION - dynamically handle OSX things that change from rev to rev
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

if (-f ../scripts/env-csh) then
   set SrcDir = $cwd
else if (-f ../../scripts/env-csh) then
   set SrcDir = $cwd:h
endif
set ldir = $SrcDir:h/scripts
set path = ( $ldir $path )
source $ldir/env-csh

set OS = `uname -r`

switch ($OS)
   case 10.*:
        setenv OSX_SHARED_LIBS ""
        setenv OSX_REV         6
        breaksw
   case 9.*:
        setenv OSX_SHARED_LIBS ""
        setenv OSX_REV         5
        breaksw
   case 8.*:
        setenv OSX_SHARED_LIBS "/usr/lib/bundle1.o -lSystemStubs -lstdc++.6.0.4"
        setenv OSX_REV         4
        breaksw
   case 7.*:
        setenv OSX_SHARED_LIBS "-lcc_dynamic /usr/lib/bundle1.o"
        setenv OSX_REV         3
        breaksw
   default:
        setenv OSX_SHARED_LIBS ""
        setenv OSX_REV         0
        breaksw
endsw

dbexp OSX_REV
dbexp OSX_SHARED_LIBS
#SetParent OSX_REV
#SetParent OSX_SHARED_LIBS

exit(0)

