#!/bin/csh -f
#
# SITE - analyze and set site information
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Me = $0
source $Me:h/common

Note $ALog "Analyze: site"

dbmget $ALog PSY_SITE   =\? ""^  \
             PSY_TYPE   =\? ""^  \
             PSY_AIRoot =\? ""^  \
             PSY_ASRoot =\? ""

if ($?DB_SITE_SIGNATURE == 1) then
   Note $ALog "DB_SITE_SIGNATURE = $DB_SITE_SIGNATURE"
else
   Note $ALog "DB_SITE_SIGNATURE not defined"
endif

if (-f $PSY_MngDir/extensions/sys-site) then
   eval `$PSY_MngDir/extensions/sys-site`
else
   eval `$PSY_ScrDir/sys-site -dc`
endif

# export the results
dbmset $ALog PSY_SITE   = $PSY_SITE^    \
             PSY_TYPE   = $PSY_TYPE^    \
             PSY_AIRoot = $PSY_AIRoot^  \
             PSY_ASRoot = $PSY_ASRoot

exit(0)

