#!/bin/csh -f
#
# RENDLR - PGS basic LR rendering tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PGS Basic Test ......... "
set exe = $BinDir/gsatst
set opt = ( -A -3 -8 -11 -12 -r 500 )
set io  = ftee

   NoteD $Log ""
   NoteD $Log -n "                    $msg"

   flog $Log pushd $SrcDir
   flog $Log $MAKE Cstd
   set xstatus = $status
   flog $Log popd

   if ($xstatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         Can't build PGS Basic Test Program"
      NoteD $Log "                    ${msg}FAILED"
   else

      source ../../../scripts/test-run

      if ($xstatus == 0) then
         flog $Log $CFE $PSDIFF gspsts.ps $RefDir/gspsts.ps
         set xstatus = $status
      endif

      flog $Log touch gsjpgt.jpg.foo
      set rpf = ( $rpf gscgmt.cgm gspsts.ps gscgmt.cgm gsjpgt.jpg.* gspngt.png.* )

      NoteD $Log ""
   endif

$TEST_CHECK part -a rendlr -e $xstatus -dt $dt -x $exe -rpf "$rpf" "$msg"

exit($status)
