#!/bin/csh -f
#
# RENDAC - PGS basic AC rendering tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PGS AC Map Test ........"
set exe = $BinDir/gsatst
set opt = ( -A -a -1 -2 -3 -4 -5 -6 -7 -8 -9 -10 )
set io  = ftee

      NoteD $Log ""
      NoteD $Log -n "                    $msg"

      source ../../../scripts/test-run

      if ($xstatus == 0) then
         flog $Log ls -l gspsta.ps $RefDir/gspsta.ps
#         flog $Log $CFE $PSDIFF gspsta.ps $RefDir/gspsta.ps
#         set xstatus = $status
      endif

      flog $Log touch gsjpgta.jpg.foo
      set rpf = ( $rpf gspsta.ps gscgmta.cgm gsjpgta.jpg.* gspngta.png.* )

      NoteD $Log ""
   endif

$TEST_CHECK part -a rendac -e $xstatus -dt $dt -x $exe -rpf "$rpf" "$msg"

exit($status)
