#!/bin/csh -f
#
# SMP - PGS parallel rendering tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PGS Parallel Test ...... "
set exe = $BinDir/gsatst

   if ("$Parallel" != "") then
      Separator $Log

      NoteD $Log ""
      NoteD $Log "                    $msg"

      if ($?IBM_BGP == 1) then
         set nthread = 2
      else
         set nthread = 4
      endif

      NoteD $Log -n "                        new ................ "
      Note $Log ""

      set rpf = "none"
      set opt = ""
      set opt = ( -t $nthread )
      set opt = ( $opt -f -A -B -D -E -F -1 -2 -3 -4 -5 -6 -7 -9 -10 -11 -12 )
      set io  = flog

      source ../../../scripts/test-run

      set rpf = ( $rpf gscgmt.cgm )

      if ($xstatus == 123) then
         set xstatus = 251
      endif

      $TEST_CHECK part -a smp_new -e $xstatus -dt $dt -l -x $exe -rpf "$rpf" none

      @ nerr = $nerr + $status

      NoteD $Log -n "                        pool ............... "
      Note $Log ""

      set rpf = "none"
      set opt = ""
      set opt = ( -t $nthread )
      set opt = ( $opt -s -A -B -D -E -F -1 -2 -3 -4 -5 -6 -7 -9 -10 -11 -12 )
      set io  = flog

      source ../../../scripts/test-run

      set rpf = ( $rpf gscgmt.cgm )

      if ($xstatus == 123) then
         set xstatus = 251
      endif

      $TEST_CHECK part -a smp_pool -e $xstatus -dt $dt -l -x $exe -rpf "$rpf" none

      @ nerr = $nerr + $status

   endif

$TEST_CHECK part -a smp -e $nerr "$msg"

exit($status)
