#!/bin/csh -f
#
# TRANS - PGS geometrical transformation tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PGS Trans Test ......... "
set exe = $BinDir/gstrts

   NoteD $Log ""
   NoteD $Log "                    $msg"

   flog $Log pushd $SrcDir
   flog $Log $MAKE trans
   set xstatus = $status
   flog $Log popd

   if ($xstatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         Can't build PGS Trans Test Program"
      NoteD $Log "                    ${msg}FAILED"
   else
      if ("$Valgrind" == "") then
         ftee $Log $CFE $exe -A
         set xstatus = $status
      else
         ftee $Log $Valgrind $exe -A           |& \
         grep "ERROR SUMMARY:"                 |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif

      Note $Log ""
   endif

$TEST_CHECK part -a trans -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)
