#!/bin/csh -f
#
# BROWSE - PDB browse test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Browse Test .................... "
set exe = $BinDir/pdlsts

NoteD $Log ""
NoteD $Log -n "                    $msg"
Note $Log ""

if ("$Valgrind" == "") then
   $CFE $exe pdatst.db >& pdatst.lst
   set xstatus = $status
else
   ftee $Log $Valgrind $exe pdatst.db           |& \
   grep "ERROR SUMMARY:"                        |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
   set rpf     = ( $rpf $Tmp )
endif

set rpf = ( $rpf pdatst.lst *.db? *.rs? )

$TEST_CHECK part -a browse -e $xstatus -x $exe -rpf "$rpf" none

exit($status)
