#!/bin/csh -f
#
# BUFB - PDB I/O buffer test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB Buffer Test B .................. "
set rpf = "none"
set exe = $BinDir/pdbtst

set STRACE = ( `which strace` )
if ("$Valgrind" == "") then

   set tst = $1

   NoteD $LogF ""
   NoteD $LogF "                    $msg"
   Note $LogF ""

# scan prime number buffer sizes
   @ lerr = 0

   foreach n ( 3 13 127 4093 32749 )
      set fill = `fill-string -n 32 $n`
      flog $LogF $CFE $exe -n -b $n

#   foreach n ( 13 127 4093 32749 )
#      set fill = `fill-string -n 32 $n`
#      flog $LogF $CFE $exe -n -b $n -v $tst

      set xstatus = $status
      if (($xstatus == 254) || ($xstatus == 255)) then
         NoteD $LogF "                        $fill (omitted)"
      else if ($xstatus == 0) then
         NoteD $LogF "                        $fill (ok)"
      else
         NoteD $LogF "                        $fill (ng)"
         @ lerr = $lerr + 1
      endif
   end
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK part -a bufb -e $xstatus -x $exe "$msg"

exit($status)
