#!/bin/csh -f
#
# BUFB - PDB I/O buffer test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set STRACE = ( `which strace` )
if ("$Valgrind" == "") then

   set tst = $1

   NoteD $LogF ""
   NoteD $LogF "                    PDB Buffer Test B .................. "
   Note $LogF ""

   set Exe = `which pdbtst`

   set UTime = `$TIMER -r`

# scan prime number buffer sizes
   @ lerr = 0

   foreach n ( 3 13 127 4093 32749 )
      set fill = `fill-string -n 32 $n`
      flog $LogF $CFE pdbtst -n -b $n

#   foreach n ( 13 127 4093 32749 )
#      set fill = `fill-string -n 32 $n`
#      flog $LogF $CFE pdbtst -n -b $n -v $tst

      set xstatus = $status
      if (($xstatus == 254) || ($xstatus == 255)) then
         NoteD $LogF "                        $fill (omitted)"
      else if ($xstatus == 0) then
         NoteD $LogF "                        $fill (ok)"
      else
         NoteD $LogF "                        $fill (ng)"
         @ lerr = $lerr + 1
      endif
   end
   set ETime   = `$TIMER -b $UTime`

   if (($xstatus == 254) || ($xstatus == 255)) then
      NoteD $LogF "                    PDB Buffer Test B .................. OMITTED ($xstatus/$ETime)"
   else if ($lerr != 0) then
      NoteD $LogF "                    PDB Buffer Test B .................. FAILED ($xstatus/$ETime)"
      set Err = 1
   else
      NoteD $LogF "                    PDB Buffer Test B .................. PASSED ($ETime)"
   endif
endif

exit($Err)
