#!/bin/csh -f
#
# C99 - PDB C99 type test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB C99 Test ....................... "
set rpf = "none"
set exe = $BinDir/pdctst

set tst = $1

NoteD $LogF ""
NoteD $LogF "                    $msg"
Note $LogF ""

if ("$Valgrind" == "") then
   ftee $LogF $CFE $exe -v $tst
   set xstatus = $status
else
   ftee $LogF $Valgrind $exe -v $tst          |& \
   grep "ERROR SUMMARY:"                      |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
   set rpf     = ( $rpf $Tmp )
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK part -a c99 -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)
