#!/bin/csh -f
#
# C99 - PDB C99 type test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB C99 Test ....................... "
set exe = $BinDir/pdctst

NoteD $Log ""
NoteD $Log "                    $msg"
Note $Log ""

set opt = ( -v $tst )
if ("$Valgrind" == "") then
   ftee $Log $CFE $exe $opt
   set xstatus = $status
else
   ftee $Log $Valgrind $exe $opt           |& \
   grep "ERROR SUMMARY:"                   |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
   set rpf     = ( $rpf $Tmp )
endif

$TEST_CHECK part -a c99 -e $xstatus -x $exe -rpf "$rpf" "$msg"

exit($status)
