#!/bin/csh -f
#
# FD - PDB file descriptor leak test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB FD Leak ........................ "
set exe = $BinDir/pdfdts

if ("$OS" != AIX) then
   if ("$Valgrind" == "") then

      NoteD $LogF ""
      NoteD $LogF -n "                    $msg"
      Note $LogF ""

      flog $LogF $CFE $exe
      set xstatus = $status

      $TEST_CHECK part -a fd -e $xstatus -x $exe none

      set xstatus = $status

   endif
endif

exit($xstatus)
