#!/bin/csh -f
#
# MASTER - PDB master test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set tst = $1

NoteD $LogF ""
NoteD $LogF "                    PDB Master Test ...................."
Note $LogF ""

set UTime = `$TIMER -r`
if ("$Valgrind" == "") then
   ftee $LogF $CFE $BinDir/pdbtst -v $tst
   set xstatus = $status
else
   ftee $LogF $Valgrind $BinDir/pdbtst -v $tst |& \
   grep "ERROR SUMMARY:"                       |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
	 flog $LogF $RM $Tmp
endif
set ETime = `$TIMER -b $UTime`

if (($xstatus == 254) || ($xstatus == 255)) then
   NoteD $LogF "                    PDB Master Test .................... OMITTED ($xstatus/$ETime)"
else if ($xstatus != 0) then
   NoteD $LogF "                    PDB Master Test .................... FAILED ($xstatus/$ETime)"
   set Err = 1
else
   NoteD $LogF "                    PDB Master Test .................... PASSED ($ETime)"
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK -a master -e $Err part

exit($status)

