#!/bin/csh -f
#
# SMP - PDB SMP parallel test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB SMP Parallel Test .............. "
set rpf = "none"
set exe = $BinDir/pdsmp

set tst = $1

if ("$Parallel" != "") then
   NoteD $LogF ""
   NoteD $LogF -n "                    $msg"
   Note $LogF ""

   flog $LogF pushd $SrcDir
   flog $LogF $MAKE smp
   set TStatus = $status
   flog $LogF popd

   if ($TStatus != 0) then
      NoteD $LogF ""
      NoteD $LogF "                         ERROR Building SMP Parallel Tests"
      NoteD $LogF "                    PDB SMP Parallel Test ......... FAILED (-1)"
      set Err = 1
   else
      if ("$Valgrind" == "") then
         flog $LogF $CFE $exe -v $tst -m 0
         set xstatus = $status
      else
         ftee $LogF $Valgrind $exe -v $tst -m 0  |& \
         grep "ERROR SUMMARY:"                   |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif
   endif
endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK part -a smp -e $xstatus -x $exe -rpf "$rpf" none

exit($status)

