#!/bin/csh -f
#
# SMP - PDB SMP parallel test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PDB SMP Parallel Test .............. "
set exe = $BinDir/pdsmp

if ("$Parallel" != "") then
   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log pushd $SrcDir
   flog $Log $MAKE smp
   set xstatus = $status
   flog $Log popd

   if ($xstatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         ERROR Building SMP Parallel Tests"
      NoteD $Log "                    ${msg}FAILED"
   else
      set opt = ( -v $tst -m 0 )
      if ("$Valgrind" == "") then
         flog $Log $CFE $exe $opt
         set xstatus = $status
      else
         ftee $Log $Valgrind $exe $opt         |& \
         grep "ERROR SUMMARY:"                 |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif
   endif
endif

$TEST_CHECK part -a smp -e $xstatus -x $exe -rpf "$rpf" none

exit($status)

