#!/bin/csh -f
#
# TYPDEF - PDB typedef test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

unalias *

source ../../tests/common

set msg = "PDB Typedef Test ................... "
set exe = $BinDir/pdtdts

NoteD $Log ""
NoteD $Log -n "                    $msg"
Note $Log ""

set opt = ( -v $tst )
if ("$Valgrind" == "") then
   flog $Log $CFE $exe $opt
   set xstatus = $status
else
   ftee $Log $Valgrind $exe $opt            |& \
   grep "ERROR SUMMARY:"                    |& \
   awk '{ print $4 }'   >&! $Tmp
   set xstatus = `cat $Tmp`
   set rpf     = ( $rpf $Tmp )
endif

if (-f out.pdb) then
   flog $Log ls -l out.pdb
   flog $Log ( grep -a Float out.pdb | grep -a double )
   if ($status == 0) then
      Note $Log "Result ok"
   else
      Note $Log "Result ng"
      flog $Log set xstatus = 2
   endif
endif

set rpf = ( $rpf out.pdb )

$TEST_CHECK part -a typdef -e $xstatus -x $exe -rpf "$rpf" none

exit($status)
