#!/bin/csh -f
#
# FUNC - PML function tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

#--------------------------------------------------------------------------

#                              PML FUNCTION TEST

#--------------------------------------------------------------------------

   NoteD $Log ""
   NoteD $Log  -n "                    PML Function Test ...... "

   flog $Log pushd $SrcDir
   flog $Log $MAKE funcs
   set TStatus = $status
   flog $Log popd

   set UTime = `$TIMER -r`

   if ($TStatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         Can't build PML Function Test Program"
      set xstatus = $TStatus
   else
      if ("$Valgrind" == "") then
         flog $LogF $CFE $BinDir/mlfnts
         set xstatus = $status
      else
         flog $Log $Valgrind $BinDir/mlfnts
         set xstatus = $status
      endif
      if ($xstatus != 0) then
        NoteD $Log ""
        NoteD $Log "                         Error in Function Test program"
      endif
   endif

   set ETime = `$TIMER -b $UTime`

   if (($xstatus == 254) || ($xstatus == 255)) then
      NoteD $Log  "                    PML Function Test ........ OMITTED ($xstatus/$ETime)"
   else if ($xstatus != 0) then
      NoteD $Log  "                    PML Function Test ........ FAILED ($ETime)"
      @ Err = 1
   else
      NoteD $Log "PASSED ($ETime)"
   endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

exit($Err)

