#!/bin/csh -f
#
# NAN - PML NAN tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PML NAN Test ........... "
set exe = $BinDir/mlnants

      NoteD $Log ""
      NoteD $Log  -n "                    $msg"

      flog $Log pushd $SrcDir
      flog $Log $MAKE fpe
      set xstatus = $status
      flog $Log popd

      if ($xstatus != 0) then
         NoteD $Log ""
         NoteD $Log "                         Can't build PML NAN Test Program"
      else
         if ("$Valgrind" == "") then
            flog $Log $cfe $exe
            set xstatus = $status
         else
            flog $Log $Valgrind $exe
            set xstatus = $status
         endif
      endif

$TEST_CHECK part -a nan -e $xstatus -x $exe none

exit($status)

