#!/bin/csh -f
#
# BASIC - PYTHON basic tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "Basic Test ....................."

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   Note $Log "PYTHONPATH = $PYTHONPATH"

   flog $Log $CFE $PYTHON $FilesDir/basic.py
   set xstatus = $status

   flog $Log touch foo.pyc
   set rpf = ( *.pyc )

$TEST_CHECK part -a basic -e $xstatus -rpf "$rpf" none

exit($status)
