#!/bin/csh -f
#
# UNIT - PYTHON unit tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "Unit Test ......................"

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   Note $Log "PYTHONPATH = $PYTHONPATH"
   Note $Log "PYTHON     = $PYTHON"
   flog $Log ls -l pact_test

   flog $Log $CROSS_FE $PYTHON $FilesDir/unittests.py
   @ xstatus = $status

   set inf = ( `grep 'FAILED (' $Log | sed 's|[()=]| |g'` )
   if ("$inf" != "") then
      if ($#inf > 4) then
         @ xstatus = $xstatus + $inf[3] + $inf[5]
      else if ($#inf > 2) then
         @ xstatus = $xstatus + $inf[3]
      endif
   endif

   flog $Log touch foo.pyc
   set rpf = ( *.pyc )

$TEST_CHECK part -a unit -e $xstatus -rpf "$rpf" none

exit($status)
