#!/bin/csh -f
#
# COMMON - support for SCHEME test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../../scripts/test-env

if ($?LogF == 0) then
   set TestName = "$0:t"

   InitLog LogF $cwd/log.$TestName.$LogSfx
endif

if ("$CFE" == "") then
   set cfe = ""
else
   set cfe = ( $CFE -v )
endif

set do_syntax = 0

if ($?Log == 1) then
   Note $Log "Log file: $LogF"
endif


