#!/bin/csh -f
#
# NUMER - SCHEME numeric tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCHEME Numeric Test .......... "
set exe = $BinDir/scheme

NoteD $Log ""
NoteD $Log "                    $msg"

flog $Log pwd

#--------------------------------------------------------------------------

#                          INTEGER SYNTAX TESTS

#--------------------------------------------------------------------------

   NoteD $Log -n "                       integer syntax ............ "
   Note $Log ""
   set rpf = none

# test that the SCHEME variable can be derived from the executable path
   flog $Log unsetenv SCHEME
   flog $Log unsetenv DO_RUN_SUBMIT_ENV

   set t0 = `$TIMER -r`
   if ("$Valgrind" == "") then
      flog $Log $cfe $exe -e -l $FilesDir/shsint.scm
      set xstatus = $status
   else
      ftee $Log $Valgrind $exe -e -l $FilesDir/shsint.scm      |& \
      grep "ERROR SUMMARY:"                                    |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

   set dt  = `$TIMER -b $t0`
   set rpf = ( $rpf '#tmp#' )

   $TEST_CHECK part -a numer_int -e $xstatus -l -dt $dt -rpf "$rpf" none

   @ nerr = $nerr + $status

#--------------------------------------------------------------------------

#                           NUMERIC TESTS

#--------------------------------------------------------------------------

   NoteD $Log -n "                       numeric ................... "
   Note $Log ""
   set rpf = none

   set t0 = `$TIMER -r`
   if ("$Valgrind" == "") then
      flog $Log $cfe $exe -e -l $FilesDir/shnum.scm
      set xstatus = $status
   else
      ftee $Log $Valgrind $exe -e -l $FilesDir/shnum.scm     |& \
      grep "ERROR SUMMARY:"                                  |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

   set dt  = `$TIMER -b $t0`
   set rpf = ( $rpf '#tmp#' )

   $TEST_CHECK part -a numer_num -e $xstatus -l -dt $dt -rpf "$rpf" none

   @ nerr = $nerr + $status

#--------------------------------------------------------------------------

#                           COMPLEX NUMERIC TESTS

#--------------------------------------------------------------------------

   NoteD $Log -n "                       complex ................... "
   Note $Log ""
   set rpf = none

   set t0 = `$TIMER -r`
   if ("$Valgrind" == "") then
      flog $Log $cfe $exe -e -l $FilesDir/shcpx.scm
      set xstatus = $status
   else
      ftee $Log $Valgrind $exe -e -l $FilesDir/shcpx.scm     |& \
      grep "ERROR SUMMARY:"                                  |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

   set dt  = `$TIMER -b $t0`
   set rpf = ( $rpf '#tmp#' )

   $TEST_CHECK part -a numer_complex -e $xstatus -l -dt $dt -rpf "$rpf" none

   @ nerr = $nerr + $status

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK part -a numer -e $nerr "$msg"

exit($status)
