#!/bin/csh -f
#
# PROC - SCHEME process tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCHEME Proc Test ............. "
set rpf = none
set exe = $BinDir/scheme

#--------------------------------------------------------------------------

#                           PROCESS TESTS

#--------------------------------------------------------------------------

   if (($CROSS_COMPILE == FALSE) && ($HaveIPC == YES)) then
      NoteD $Log ""
      NoteD $Log -n "                    $msg"
      Note $Log ""

      if ("$Valgrind" == "") then
         $CFE $exe -e -l $FilesDir/shproc.scm >! shproc.res
         set xstatus = $status
      else
         ftee $Log $Valgrind $exe -e -l $FilesDir/shproc.scm     |& \
         grep "ERROR SUMMARY:"                                   |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif

      set rpf = ( $rpf shproc.res shproc.res.diff )
   else
      set xstatus = 0
   endif

$TEST_CHECK part -a proc -e $xstatus -rpf "$rpf" none

exit($status)
