#!/bin/csh -f
#
# STRING - SCHEME string test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCHEME String Test ........... "
set rpf = none
set exe = $BinDir/scheme

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log pwd

   if ("$Valgrind" == "") then
      flog $Log $cfe $exe -e -l $FilesDir/shstr.scm
      set xstatus = $status
   else
      ftee $Log $Valgrind $exe -e -l $FilesDir/shstr.scm     |& \
      grep "ERROR SUMMARY:"                                  |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

$TEST_CHECK part -a string -e $xstatus -rpf "$rpf" none

exit($status)
