#!/bin/csh -f
#
# SCS-MOVE - rename sources whether SCSI, CVS or SVN
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

unalias *

set ldir = `dirname $0`
if ("$ldir" == ".") then
   set ldir = $cwd
endif
set scsi = ( `$ldir/which-scs` )

switch ($scsi[1])
   case git:
        git mv $argv
        breaksw

   case cvs:
        setenv CVS_RSH  ssh

        set old = $1
        set new = $2

        mv $old $new
        cvs remove $old
        cvs add $new
        breaksw

   case svn:
        svn mv $argv
        breaksw
endsw

exit($status)
