#!/bin/csh -f
#
# SCS-MOVE - rename sources whether GIT, CVS or SVN
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

unalias *

set ldir = `dirname $0`
if ("$ldir" == ".") then
   set ldir = $cwd
endif
set gitd = ( `$ldir/where-git` )

if (-d $gitd[1]) then

   pushd $gitd[1] >& /dev/null
   git mv $argv
   popd >& /dev/null

else if (-d CVS) then

   set old = $1
   set new = $2

   mv $old $new
   cvs remove $old
   cvs add $new

else if (-d .svn) then

   svn mv $argv

endif

exit($status)
