#!/bin/csh -f
#
# SCS-ADD - add to repository whether GIT, CVS or SVN
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

unalias *

set ldir = `dirname $0`
set gitd = ( `$ldir/where-git` )

if (-d $gitd[1]) then

   git add $argv

else if (-d CVS) then

   cvs add $argv

else if (-d .svn) then

   svn add $argv

endif

exit($status)
