#!/bin/csh -f
#
# PCO - test pco
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/psh/tests/common

set msg = "PCO Test ......................."

while ($#argv > 0)
   switch ($1)
      case -h:
           echo ""
           echo "Usage: pco [-h]"
           echo "  h  this help message"
           echo ""
           exit(1);
      default:
           breaksw
   endsw
   shift
end

NoteD $Log ""
NoteD $Log "                    $msg"
Note $Log ""

flog $Log pushd ../../../manager

# GOTCHA: need a lighter weight test for the greater test suite
#   flog $Log ./test-pco

if ($IBM_HW !~ BG*) then
   ftee $Log ../psh/tests/pco-cmp
   set xstatus = $status
endif

flog $Log popd

$TEST_CHECK part -a pco -e $xstatus -rpf "$rpf" $msg

exit($status)

