#!/bin/csh -f
#
# PERDB5 - test reset and load
#        - no FIFO
#

unalias *

@ err = 0

set opt = "-l"
set db  = ./db5

alias dbset     'set t_ = ( `perdb $opt \!\!:1 = \!\!:2-$` ) ; setenv \!\!:1 "$t_" ; unset t_'
alias dbget     'setenv \!\!:1 "`perdb $opt \!\!:1`"'

rm -f db5-* >& /dev/null

setenv PERDB_PATH $db

echo "-----------------------------------"

dbset v1 a
echo "v1 = `printenv 'v1'`"

dbset v2 b
echo "v2 = `printenv 'v2'`"

dbset v3 c
echo "v3 = `printenv 'v3'`"

echo ""
perdb $opt save:dba:
@ err = $err + $status

echo "-----------------------------------"

dbset v2 w
echo "v2 = `printenv 'v2'`"

dbset v3 x
echo "v3 = `printenv 'v3'`"

dbset v4 y
echo "v4 = `printenv 'v4'`"

dbset v5 z
echo "v5 = `printenv 'v5'`"

echo ""
perdb $opt save:dbb:
@ err = $err + $status

echo "-----------------------------------"

perdb $opt reset:
@ err = $err + $status
perdb $opt load:dba:
@ err = $err + $status

dbget v2
echo "v2 : |$v2|"

dbget v3
echo "v3 : |$v3|"

dbget v4
echo "v4 : |$v4|"

echo "-----------------------------------"

perdb $opt save:csh:stdout:
@ err = $err + $status

echo "-----------------------------------"

perdb $opt save:csh:stdout: v1 v3 v5
@ err = $err + $status

echo "-----------------------------------"

perdb $opt save:sh:stdout:
@ err = $err + $status

echo "-----------------------------------"

perdb $opt save:sh:stdout: v1
@ err = $err + $status

echo "-----------------------------------"

perdb $opt quit:
@ err = $err + $status

exit($err)
