#!/bin/csh -f
#
# S6T1 - test 1 of signature file 6
#      - pure parse test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set exe = do-run
set tgt = ans
set opt = ( -level 3 -dr -mpi foo -s run.s6 s6t1 )
set io  = none

while ($#argv > 0)
   switch ($1)
      case -c:
           shift
           set exe = $1
           breaksw
      case '-h':
           echo "Usage: $0 [-c <code>] [-h] run | ans"
           echo "   c     test <code> (default do-run on path)"
           echo "   h     this help message"
           echo "   run   run the test"
           echo "   ans   print the fiducial answer"
           echo ""
           exit(1)
      default:
           set tgt = $1
           breaksw
   endsw
   shift
end

if ($tgt == run) then
   source $PSY_Base/scripts/test-run

# print the fiducial answer for this test
else
   echo "Using signature file 'run.s6'"
   echo 'CROSS = '
   echo 'MPI   = foo'
   echo '> setenv Cmd foo'
   echo '> if ( 1 = 1 ) {val} else {}'
   echo '>    Consequent: val'
   echo '> setenv var1 val'
   echo '> if ( 1 -ne 0 ) {val} else {}'
   echo '>    Consequent: val'
   echo '> setenv var2 val'
   echo '> if ( ( 1 = 1 ) -a ( 0 = 0 ) ) {a} else {b}'
   echo '>    Consequent: a'
   echo '> setenv var3 a'
   echo '> if ( ( 1 = 1 ) -o ( 0 = 0 ) ) {a} else {b}'
   echo '>    Consequent: a'
   echo '> setenv var4 a'
   echo '> if ( "abc" =~ *b* ) {a} else {b}'
   echo '>    Consequent: a'
   echo '> setenv var5 a'
   echo '> if ( "abc" =~ *d* ) {a} else {b}'
   echo '>    Alternate: b'
   echo '> setenv var5 b'
   echo '> if ( "abc" !~ *b* ) {a} else {b}'
   echo '>    Alternate: b'
   echo '> setenv var6 b'
   echo '> if ( "abc" !~ *d* ) {a} else {b}'
   echo '>    Consequent: a'
   echo '> setenv var6 a'
   echo 'foo'
   set xstatus = 0
endif

echo "xstatus = $xstatus"

exit(0)
