#!/bin/csh -f
#
# AXIS - SX AXIS test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

#--------------------------------------------------------------------------

#                           AXIS TEST

#--------------------------------------------------------------------------

   NoteD $Log ""
   NoteD $Log -n "                    SX AXIS Test ................. "
   Note $Log ""

   set UTime = `$TIMER -r`
   if ("$Valgrind" == "") then
      flog $Log $SX -l $TDir/sxaxs.scm
      set xstatus = $status
      if ($xstatus == 0) then
         flog $Log ( $CFE $PSDIFF sxaxs.ps $RefDir/sxaxs.ps > sxaxs.ps.diff )
         set xstatus = $status
      endif
   else
      ftee $Log $Valgrind $BinDir/sx -e -r -s -l $TDir/sxaxs.scm |& \
      grep "ERROR SUMMARY:"                                      |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      flog $Log $RM $Tmp
   endif

   set ETime = `$TIMER -b $UTime`

   if (($xstatus == 254) || ($xstatus == 255)) then
      NoteD $LogF "OMITTED ($xstatus/$ETime)"
   else if ($xstatus != 0) then
      NoteD $Log "FAILED ($xstatus/$ETime)"
      set Err = 1
   else
      NoteD $Log "PASSED ($ETime)"
      flog $Log $RM sxaxs.*
   endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

exit($Err)
