#!/bin/csh -f
#
# COMMON - support for SX test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

setenv Package  sx
setenv Test     $0:t
source ../../../scripts/test-env

set sxopt = ( -e -r -s $ZeroSpace )
set pvopt = ( -p -e -r -q $ZeroSpace )

if ("$CROSS_FE" == "") then
   set cross_fe = ""
else
   set cross_fe = ( $CROSS_FE -v )
endif

foreach v (THREADING HAVE_MPI HAVE_SQLITE HAVE_HDF5)
   grep "#define $v" $IncDir/scconfig.h >& /dev/null
   if ($status == 0) then
      setenv $v yes
   else
      setenv $v no
   endif
end

