#!/bin/csh -f
#
# COMMON - support for SX test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../../scripts/test-env

#if ($?LogF == 0) then
#   InitLog LogF $cwd/log.$TestName.$LogSfx
#endif

set TestName = "$0"
set TestName = "$TestName:t"

if ("$CFE" == "") then
   set cfe = ""
else
   set cfe = ( $CFE -v )
endif

grep '#define THREADING' $IncDir/scconfig.h >& /dev/null
if ($status == 0) then
   setenv THREADING yes
else
   setenv THREADING no
endif

grep '#define HAVE_MPI' $IncDir/scconfig.h >& /dev/null
if ($status == 0) then
   setenv HAVE_MPI yes
else
   setenv HAVE_MPI no
endif

grep '#define HAVE_SQLITE' $IncDir/scconfig.h >& /dev/null
if ($status == 0) then
   setenv HAVE_SQLITE yes
else
   setenv HAVE_SQLITE no
endif

#set PDBDiff = "$BinDir/pdbdiff -e -x -q $ZeroSpace"

if ($?Log == 1) then
   Note $Log "Log file: $LogF"
endif


