#!/bin/csh -f
#
# OPER - SX operator tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

#--------------------------------------------------------------------------

#                           OPER TEST

#--------------------------------------------------------------------------

   if ("$MPI" == "") then
      NoteD $Log ""
      NoteD $Log -n "                    SX OPER Test ................. "
      Note $Log ""

      flog $Log rm -f sxoper.res

      set UTime = `$TIMER -r`
      if ("$Valgrind" == "") then
         flog $Log ($CFE $PDBView -l $RootDir/sx/tests/sxoper.scm > sxoper.res)
         set xstatus = $status
      else
         ftee $Log $Valgrind $BinDir/sx -e -p -q -l $RootDir/sx/tests/sxoper.scm |& \
         grep "ERROR SUMMARY:"                                                   |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         flog $Log $RM $Tmp
      endif

      set ETime = `$TIMER -b $UTime`

      if ($xstatus != 0) then
         NoteD $Log "FAILED ($xstatus/$ETime)"
         set Err = 1
      else
         flog $Log rm -f sxoper.res arr.dat sxoper*.ps
         NoteD $Log "PASSED ($ETime)"
      endif
   endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

exit($Err)
