#!/bin/csh -f
#
# PDB - ULTRA PDB test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SX PDB Test .................. "
set exe = $BinDir/sx
set opt = ( -e -r -s $ZeroSpace -l $RootDir/sx/tests/sxpdb.scm )
set io  = flog

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log cp $TDir/sxpdbg.scm .

   if ("$Valgrind" == "") then
      flog $Log ($exe $opt > sxpdb.res)
      set xstatus = $status
   else
      ftee $Log $Valgrind $exe $opt     |& \
      grep "ERROR SUMMARY:"             |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

   if ($xstatus == 0) then
      flog $Log (diff sxpdb.res $RootDir/sx/tests/ref/sxpdb > sxpdb.res.diff)
      set xstatus = $status
   endif

   set rpf = ( $rpf sxpdb.res sxpdb.res.diff )

$TEST_CHECK part -a pdb -e $xstatus -rpf "$rpf" none

exit($status)
