#!/bin/csh -f
#
# SHELL - PDBVIEW shell tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

#--------------------------------------------------------------------------

#                           SHELL TESTS

#--------------------------------------------------------------------------

   if (($CROSS_COMPILE == FALSE) && ($HaveIPC == YES)) then
      NoteD $Log ""
      NoteD $Log "                    PDBView Shell Test ........... "

      set UTime = `$TIMER -r`
      $CFE $FilesDir/pdbvenv.scm >&! pdbvenv.res
      set xstatus = $status
      diff pdbvenv.res $FilesDir/ref/pdbvenv >&! pdbvenv.res.diff
      set dstatus = $status
      set ETime = `$TIMER -b $UTime`

      if (($xstatus != 0) || ($dstatus != 0)) then
         flog $Log cat pdbvenv.res
         flog $Log cat pdbvenv.res.diff
         set xstatus = 1
      endif
      if ($xstatus != 0) then
         NoteD $Log "                       env ....................... ng ($xstatus/$ETime)"
         set Err = 1
      else
         NoteD $Log "                       env ....................... ok ($ETime)"
         flog $Log rm -f pdbvenv.res pdbvenv.res.diff
      endif

      set UTime = `$TIMER -r`
      $CFE $FilesDir/pdbvexe.scm a 1 2.3 '"abc"' >&! pdbvexe.res
      set xstatus = $status
      diff pdbvexe.res $FilesDir/ref/pdbvexe >&! pdbvexe.res.diff
      set dstatus = $status
      set ETime = `$TIMER -b $UTime`

      if (($xstatus != 0) || ($dstatus != 0)) then
         flog $Log cat pdbvexe.res
         flog $Log cat pdbvexe.res.diff
         set xstatus = 1
      endif
      if ($xstatus != 0) then
         NoteD $Log "                       argv ...................... ng ($xstatus/$ETime)"
         set Err = 1
      else
         NoteD $Log "                       argv ...................... ok ($ETime)"
         flog $Log rm -f pdbvexe.res pdbvexe.res.diff
      endif

      if ($Err == 0) then
         NoteD $Log "                    PDBView Shell Test ........... PASSED"
      else
         NoteD $Log "                    PDBView Shell Test ........... FAILED"
      endif
   endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

exit($Err)
