#!/bin/csh -f
#
# XML - SX XML DB test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SX PDB XML Test .............. "
set exe = $BinDir/sx

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   set Ref = $RootDir/sx/tests/ref/sxxml

   flog $Log rm -f sxxml.log sxxml.res foo.xml

   flog $Log cp $TDir/txml* .

   set opt = ( -l $RootDir/sx/tests/sxxml.scm )
   if ("$Valgrind" == "") then
      flog $Log ($PDBView $opt >& sxxml.res)
      set xstatus = $status
      if ($xstatus == 0) then
         if (-f $Ref) then
            flog $Log diff sxxml.res $Ref
            set xstatus = $status
         else
            flog $Log cp sxxml.res $Ref
         endif
      endif
   else
      ftee $Log $Valgrind $exe -e -p -q $opt     |& \
      grep "ERROR SUMMARY:"                      |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

   flog $Log touch foo.sxxml sxxml.foo
   set rpf = ( $rpf sxxml.* *.sxxml )

$TEST_CHECK part -a xml -e $xstatus -rpf "$rpf" none

exit($status)

