#!/bin/csh -f
#
# CPP2 - basic test of acpp with error
#      - should have no output on error
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set xstatus = 0

# run the test
if ($1 == run) then
   set tmp = $cwd/cpp2
   cat >! $tmp.h << EOF
#define a b
int a;

#if 1
#error "bad, bad"
#endif

EOF

   acpp -o - $tmp.h
   if ($status == 0) then
      set xstatus = 1
   else
      set xstatus = 0
   endif


# print the fiducial answers
else

endif

exit($xstatus)
