#!/bin/csh -f
#
# DOBATCH - test do-batch
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "DO-BATCH Test .................."

set lst = ""

while ($#argv > 0)
   switch ($1)
      case -h:
           echo ""
           echo "Usage: dobatch [-h]"
           echo "   h  this help message"
           echo ""
           exit(1);
      default:
           set lst = ( $lst $1 )
           breaksw
   endsw
   shift
end

if ($CROSS_COMPILE == FALSE) then

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# DOB - test functions-pact

   NoteD $Log -n "                    $msg"

   flog $Log cp $FilesDir/bat? .
   flog $Log batp date -d 1/1/2001
   set xstatus = $status

   sleep 10

   @ nerr = $nerr + $xstatus
   if ($xstatus == 0) then
      flog $Log ls -lR tmp-* wrk-*
      flog $Log cat wrk-*/v*/res*
      flog $Log rm -rf tmp-* wrk-*
   endif

   set rpf = ( $rpf b.g.* batl batp )

   $TEST_CHECK part -a dobatch -e $nerr -rpf "$rpf" none

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

endif

exit($status)
