#!/bin/csh -f
#
# BUF - test SCORE I/O buffering
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/score/tests/common

set msg = "SCORE Buffered I/O Test ......."
set exe = $BinDir/tscbf
set opt = ""
set io  = ftee

NoteD $Log ""
NoteD $Log "                    $msg"

flog $Log pushd $SrcDir
flog $Log $MAKE io
set xstatus = $status
flog $Log popd

if ($xstatus == 0) then
   source $PSY_Base/scripts/test-run
endif

$TEST_CHECK part -a buf -e $xstatus -dt $dt -x $exe -rpf "$rpf" "$msg"

exit($status)

