#!/bin/csh -f
#
# MAKE - test dmake
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/score/tests/common

set msg = "SCORE Make Test ..............."
set exe = $BinDir/dmake

if ($CROSS_COMPILE == FALSE) then
   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   NoteD $Log ""

   flog $Log pushd $FilesDir
   ftee $Log do-test $argv
   set xstatus = $status
   flog $Log popd

# NOTE: exit status is sum of values for each test
#   basic  fails -> 32
#   depend fails -> 16
#   script fails -> 8
#   redir  fails -> 4
#   server fails -> 2
#   async  fails -> 1
# server and async are currently prone to race type failures
# so do not fail the test if they do not succeed

endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK part -a mk -e $xstatus -rpf "$rpf" "$msg"

exit($status)

