#!/bin/csh -f
#
# MMAP - test memory mapped I/O facilities in SCORE
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/score/tests/common

set msg = "SCORE Mapped File Test ........"
set exe = $BinDir/tscmf
set opt = ""
set io  = ftee

if ($CROSS_COMPILE == FALSE) then

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   NoteD $Log ""

   flog $Log pushd $SrcDir
   flog $Log $MAKE mf
   set xstatus = $status
   flog $Log popd

   if ($xstatus == 0) then
      source $PSY_Base/scripts/test-run
   endif

   touch mft.foo
   set rpf = ( $rpf mft.* )
   rm mft.foo

endif

$TEST_CHECK part -a mmap -e $xstatus -dt $dt -x $exe -rpf "$rpf" "$msg"

exit($status)

