#!/bin/csh -f
#
# RETRC - test SCORE retrace facility
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/score/tests/common

set msg = "SCORE Retrace Test ............"
set exe = $BinDir/tscrtr
set opt = ""
set io  = flog

# do not do this test if cross compiling, using valgrind, or running OSX
# technically OSX 10.8 is bad, but OSX policy changes make debugging
# problematic - codesigning, admin privileges required to use ptrace
if (($CROSS_COMPILE == FALSE) && ($HSY_OS_Name != Darwin ) && ("$Valgrind" == "")) then

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log pushd $SrcDir
   flog $Log $MAKE retrace
   set xstatus = $status
   flog $Log popd

   if ("$CROSS_FE" != "") then
      setenv CROSS_FE   "$CROSS_FE -v"
   endif

   source $PSY_Base/scripts/test-run

   $TEST_CHECK part -a retrc -e $xstatus -dt $dt -x $exe -rpf "$rpf" none

   set xstatus = $status

endif

exit($xstatus)

