#!/bin/csh -f
#
# PIPE - PPC pipe tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "PPC Pipe Test .................."
set exe = $BinDir/pcexec

      NoteD $Log ""
      NoteD $Log "                    $msg "

      flog $Log rm -f pcexec.refi pcexec.refp

      NoteD $Log -n "                       polling ....................."
      set rpf = "none"
      set opt = ( -i -c 30 -p $TEST )
      set io  = pcexec.refp

      source ../../../scripts/test-run

      $TEST_CHECK part -a pipe_poll -e $xstatus -dt $dt -l -rpf "$rpf" none

      @ nerr = $nerr + $status

      NoteD $Log -n "                       interrupt ..................."
      set rpf = "none"
      set opt = ( -c 30 -p $TEST )
      set io  = pcexec.refi

      source ../../../scripts/test-run

      $TEST_CHECK part -a pipe_interrupt -e $xstatus -dt $dt -l -rpf "$rpf" none

      @ nerr = $nerr + $status

$TEST_CHECK part -a pipe -e $nerr "$msg"

exit($status)

