#!/bin/csh -f
#
# PTY - PPC pty tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set DPE = ""
set msg = "PPC PTY Test ..................."
set exe = $BinDir/pcexec

# this test fails too often on DP machines so don't run there
      if ("$DPE" == "") then
         NoteD $Log ""
         NoteD $Log "                    $msg "

         flog $Log rm -f pcexec.ptyi pcexec.ptyp

         NoteD $Log -n "                       polling ..................... "
         set rpf = "none"
         set opt = ( -i -c 30 -t $TEST )
         set io  = pcexec.ptyp

         source ../../../scripts/test-run

#         if ("$Valgrind" == "") then
#            $CFE $exe $opt | tr -d "\015" > pcexec.ptyp
#            set xstatus = $status
#         else
#            ftee $Log $Valgrind $exe $opt       |& \
#            grep "ERROR SUMMARY:"               |& \
#            awk '{ print $4 }'   >&! $Tmp
#            set xstatus = `cat $Tmp`
#            set rpf     = ( $rpf $Tmp )
#         endif

         $TEST_CHECK part -a pty_poll -e $xstatus -dt $dt -l -rpf "$rpf" none

         @ nerr = $nerr + $status

         NoteD $Log -n "                       interrupt ................... "
         set rpf = "none"
         set opt = ( -c 30 -t $TEST )
         set io  = pcexec.ptyi

         source ../../../scripts/test-run

#         if ("$Valgrind" == "") then
#            $CFE $exe $opt | tr -d "\015" > pcexec.ptyi
#            set xstatus = $status
#         else
#            ftee $Log $Valgrind $exe $opt        |& \
#            grep "ERROR SUMMARY:"                |& \
#            awk '{ print $4 }'   >&! $Tmp
#            set xstatus = `cat $Tmp`
#	    set rpf     = ( $rpf $Tmp )
#         endif

         $TEST_CHECK part -a pty_interrupt -e $xstatus -dt $dt -l -rpf "$rpf" none

         @ nerr = $nerr + $status

         if ($xstatus != 0) then
            if ("$Valgrind" == "") then
               diff pcexec.refi pcexec.ptyi > pcexec.diffi
               set Files = `find . -name "pcexec.diffi" -size 0c -print`
               diff pcexec.refp pcexec.ptyp > pcexec.diffp
               set Files = `find . -name "pcexec.diffp" -size 0c -print`
            else
               set Files = 1
            endif
            if ($#Files == 0) then
               @ nerr = $nerr + 1
            endif
         endif
         set rpf = ( pcexec.diff* pcexec.pty* pcexec.ref* )

      endif

$TEST_CHECK part -a pty -e $xstatus -rpf "$rpf" "$msg"

exit($status)

