#!/bin/csh -f
#
# ANNOT - ULTRA annotation test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "ULTRA Annotation Test ........ "
set exe = $BinDir/ultra

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   set opt = ( -l $TDir/ulann.scm )  
   if ("$Valgrind" == "") then
      flog $Log ($CFE $Ultra $opt >&! ulmmt.log)
      set xstatus = $status
   else
      ftee $Log $Valgrind $exe -e -r -x -q -s $opt    |& \
      grep "ERROR SUMMARY:"                           |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = $Tmp
   endif

$TEST_CHECK part -a annot -e $xstatus -rpf "$rpf" none

exit($status)
