#!/bin/csh -f
#
# COMMON - support for ULTRA test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../../scripts/test-env

if ($?LogF == 0) then
   set TestName = "$0:t"

endif

if ("$CFE" == "") then
   set cfe = ""
else
   set cfe = ( $CFE -v )
endif

if ($?Log == 1) then
   Note $Log "Log file: $LogF"
endif

