#!/bin/csh -f
#
# COMMON - support for ULTRA test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

setenv Package  ultra
setenv Test     $0:t
source ../../../scripts/test-env

if ("$CFE" == "") then
   set cfe = ""
else
   set cfe = ( $CFE -v )
endif

