#!/bin/csh -f
#
# FFT - ULTRA FFT test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "ULTRA FFT Test ............... "
set exe = $BinDir/ultra

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log $RM ulfft.log ulfft.err

   set opt = ( -l $TDir/ulfft.scm )
   if ("$Valgrind" == "") then
      flog $Log ($CFE $Ultra $opt >&! ulfft.log)
      set xstatus = $status
      flog $Log (grep -i "error" ulfft.log >&! ulfft.err)
   else
      ftee $Log $Valgrind $exe -e -r -x -q -s $opt      |& \
      grep "ERROR SUMMARY:"                             |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = $Tmp
   endif

$TEST_CHECK part -a fft -e $xstatus -rpf "$rpf" none

exit($status)
