#!/bin/csh -f
#
# FILL - ULTRA FILL test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "ULTRA FILL Test .............. "
set exe = $BinDir/ultra

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log $RM ulfill.log ulfill.err

   set opt = ( -l $TDir/ulfill.scm )
   if ("$Valgrind" == "") then
      flog $Log ($CFE $Ultra $opt >&! ulfill.log)
      set xstatus = $status
      flog $Log (grep -i "error" ulfill.log >&! ulfill.err)
   else
      ftee $Log $Valgrind $exe -e -r -x -q -s $opt     |& \
      grep "ERROR SUMMARY:"                            |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = $Tmp
   endif

$TEST_CHECK part -a fill -e $xstatus -rpf "$rpf" none

exit($status)

