#!/bin/csh -f
#
# FNC - ULTRA function test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "ULTRA FNC Test ............... "
set exe = $BinDir/ultra
set opt = ( -e -r -x -q -s $ZeroSpace -l $TDir/ulfnc.scm )
set io  = ulfnc.log

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log $RM ultest.err ulfnc.log

# CYGWIN 1.5 simply will not write output to ulfnc.log
# the other tests are fine
   if ($OS =~ CYGWIN*) then
      flog $Log $cfe $exe $opt
      set xstatus = $status
   else
      source ../../../scripts/test-run
   endif

   flog $Log (grep -i "error" ulfnc.log >&! ultest.err)

$TEST_CHECK part -a fnc -e $xstatus -rpf "$rpf" none

exit($status)
