#!/bin/csh -f
#
# MEM - ULTRA memory test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "ULTRA Memory Test ............ "
set exe = $BinDir/ultra
set opt = ( -e -r -x -q -s $ZeroSpace -n -l $TDir/ulmmt.scm )
set io  = flog

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   if ("$Valgrind" == "") then
      flog $Log ($CFE $exe $opt >& ulmmt.log)
      set xstatus = $status
   else
      ftee $Log $Valgrind $exe $opt      |& \
      grep "ERROR SUMMARY:"              |& \
      awk '{ print $4 }'   >&! $Tmp
      set xstatus = `cat $Tmp`
      set rpf     = ( $rpf $Tmp )
   endif

$TEST_CHECK part -a mem -e $xstatus -rpf "$rpf" none

exit($status)
