#!/bin/csh -f
#
# COMMON - support for SCORE test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set Package = score
source ../../../scripts/test-env

if ($?LogF == 0) then
   set TestName = "$0:t"

   InitLog LogF $cwd/log.$TestName.$LogSfx
endif

if ($?Log == 1) then
   Note $Log "Log file: $LogF"
endif

