#!/bin/csh -f
#
# MOR - malloc override test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

if ($CROSS_COMPILE == FALSE) then

   NoteD $LogF ""
   NoteD $LogF -n "                    SCORE Override Test ......... "
   NoteD $LogF ""

   set UTime = `$TIMER -r`

   flog $LogF pushd $SrcDir
   flog $LogF $MAKE memovr
   set xstatus = $status
   Note $LogF "make status = $xstatus"

   flog $LogF popd

   if ($xstatus == 0) then
      flog $LogF setenv LD_LIBRARY_PATH  $LibDir
      flog $Log ldd $BinDir/scmots
      if ("$Valgrind" == "") then
         ftee $LogF ( ( setenv LD_PRELOAD $LibDir/libosmm.so ; $CFE $BinDir/scmots ) |& grep -v "Dwarf Error" |& grep -iwv error )
         set xstatus = $status
      endif
      flog $LogF unsetenv LD_PRELOAD
      flog $LogF unsetenv LD_LIBRARY_PATH
   else
      Note $LogF "Failed to build scmots - skipping"
      set xstatus = 0
   endif

   set ETime = `$TIMER -b $UTime`

   if (($xstatus == 254) || ($xstatus == 255)) then
      NoteD $LogF "                    SCORE Override Test ......... OMITTED ($xstatus/$ETime)"
   else if ($xstatus != 0) then
      NoteD $LogF "                    SCORE Override Test ......... FAILED ($xstatus/$ETime)"
      set Err = 1
   else
      NoteD $LogF "                    SCORE Override Test ......... PASSED ($ETime)"
   endif

endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

$TEST_CHECK -a mor -e $Err part
set status = 0

exit($status)

