#!/bin/csh -f
#
# MOR - malloc override test
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE Override Test ..........."
set exe = $BinDir/scmots
set opt = ""
set io  = ftee

if (($CROSS_COMPILE == FALSE) && ($PACT_CC_FAMILY != INTEL)) then

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   NoteD $Log ""

   flog $Log pushd $SrcDir
   flog $Log $MAKE memovr
   set xstatus = $status
   Note $Log "make status = $xstatus"

   flog $Log popd

   if ($xstatus == 0) then
      flog $Log ldd $exe
      if ("$Valgrind" == "") then
#         ftee $Log ( ( setenv LD_PRELOAD $LibDir/libosmm.so ; $CFE $exe ) |& grep -v "Dwarf Error" |& grep -iwv error )
#         ftee $Log ( ( setenv LD_PRELOAD $LibDir/libosmm.so ; $CFE $exe ) |& grep -v "Dwarf Error" )
#         ftee $Log ( setenv LD_PRELOAD $LibDir/libosmm.so ; $CFE $exe )
         ftee $Log $CFE $exe
         set xstatus = $status
      endif
   else
      Note $Log "Failed to build scmots - skipping"
      set xstatus = 0
   endif

   $TEST_CHECK part -a mor -e $xstatus -x $exe -rpf "$rpf" "$msg"

   set xstatus = $status

endif

exit($xstatus)

