#!/bin/csh -f
#
# RETRC - test SCORE retrace facility
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCORE Retrace Test ............ "
set exe = $BinDir/scrtrt
set opt = ""
set io  = flog

if ($CROSS_COMPILE == FALSE) then

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log pushd $SrcDir
   flog $Log $MAKE retrace
   set xstatus = $status
   flog $Log popd

   if ("$CFE" != "") then
      setenv CFE   "$CFE -v"
   endif

   source ../../../scripts/test-run

endif

$TEST_CHECK part -a retrc -e $xstatus -dt $dt -x $exe -rpf "$rpf" none

exit($status)

