#!/bin/csh -f
#
# MODULE-CRAY - load specified compiler module for XE6 compilations
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set cmp   = ""
set cvers = ""
set evers = ""

while ($#argv > 0)
   switch ($1)
      case -h:
           echo ""
           echo "Usage: module-cray env <version> <compiler> <version>"
           echo ""
           exit(1)
      case env:
           shift
           set evers = $1
           breaksw
      default:
           if ("$cmp" == "") then
              set cmp   = $1
              set cvers = $1
              shift
           endif
           breaksw
   endsw
   shift
end

if ("$cmp" == "") then
   echo "No compiler specified - exiting"
   exit(1)
endif

if ("$cvers" == "") then
   echo "No compiler version specified - exiting"
   exit(1)
endif

if ("$evers" == "") then
   echo "No environment version specified - exiting"
   exit(1)
endif

if ($cmp == gnu) then
   set cc = gcc
else
   set cc = $cmp
endif

if ($?MODULESHOME == 1) then

   alias setp   'setenv \!* ; echo "parent \!\!:1($\!\!:1)"'
   alias unsetp 'echo "\!*"'

# unload any currently loaded modules
   set mlst = ( `echo $PRGENVMODULES | sed 's|:| |g'` )
   foreach mod ($mlst)
      eval `$MODULESHOME/bin/modulecmd tcsh unload $mod`
   end

# load and export the requested environment module
   eval `$MODULESHOME/bin/modulecmd tcsh load PrgEnv-$cmp/$evers | sed 's|setenv|setp|g'`

# load and export the requested compiler module
   eval `$MODULESHOME/bin/modulecmd tcsh load $cc/$cvers | sed 's|setenv|setp|g'`

   foreach i ($LD_LIBRARY_PATH)
      setenv RPATH `analyze/rpath -a $i -o echo`
   end

   setp DP_Inc     -I$MPICH_DIR/include
   setp DP_Lib     -lmpich
   setp DP_RPath   $MPICH_DIR/lib
   setp RPATH      $RPATH

endif

exit($status)

