#!/bin/csh -f
#
# SVD - PML SVD tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source $PSY_Base/pml/tests/common

set msg = "PML SVD Test ..........."
set exe = $BinDir/tmlsvd
set opt = ""
set io  = flog

   NoteD $Log ""
   NoteD $Log -n "                    $msg"

   flog $Log pushd $SrcDir
   flog $Log $MAKE svdsolv
   set xstatus = $status
   flog $Log popd

   if ($xstatus != 0) then
      NoteD $Log ""
      NoteD $Log "                         Can't build PML SVD Test Program"
   else
      source $PSY_Base/scripts/test-run
   endif

$TEST_CHECK part -a svd -e $xstatus -dt $dt -x $exe none

exit($status)

