#!/bin/csh -f
#
# LBIND - generate wrappers of C functions for SCHEME and Fortran
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

unalias *

set err  = 0
set arch = `../scripts/cfgman use`

source ../scripts/env-csh

InitLog Log $cwd:h/dev/$arch/log/lbind

Note $Log ""
NoteD $Log "Generating C bindings for Fortran, SX, and Python"
Note $Log ""

flog $Log pushd ../psh
flog $Log pact elide
flog $Log pact blang
flog $Log popd

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

# GENERATE - generate interfaces for each package

flog $Log set Dirs = ( score pml pdb ppc pgs panacea scheme sx ultra )
foreach d ($Dirs)

   Separator $Log
   flog $Log pushd ../$d

   ftee $Log ../scripts/bproto

   flog $Log popd
end

exit($err)

