#!/bin/csh -f
#
# SCSTAG - tag a source version whether GIT, CVS or SVN
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

unalias *

if (-d .git) then

   git tag $argv

else if (-d CVS) then

   cvs tag $argv

else if (-d .svn) then

   svn tag $argv

endif

exit($status)
