#!/bin/csh -f
#
# SCSUP - update sources whether CVS or SVN
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set cvsopt = ""
set svnopt = ""
set args   = ""
while ($#argv > 0)
   switch ($1)
      case -l:
           set cvsopt = ( $cvsopt -l )
           set svnopt = ( $svnopt --depth files )
           breaksw
      default:
           set args = ( $args $1 )
           breaksw
   endsw
   shift
end

if (-d CVS) then

   cvs update $cvsopt $args |& egrep -v '^\?' |& grep -v 'cvs update'

else if (-d .svn) then

   svn update $svnopt $args
   svn status $svnopt |& egrep -v '^\?'

endif

exit($status)
