#!/bin/csh -f
#
# WHICH-DMAKE - find a dmake version that will work in CROSS-COMPILE situation
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

@ err = 1

set mk    = ""
set extra = ""
set sys   = `system-id`

if ($?DAS_ROOT == 1) then
   set extra = ( $DAS_ROOT/pactnew/bin/pact $DAS_ROOT/pact/bin/pact )
endif

foreach d ( ../dev/*/bin/dmake $extra )
   set path = ( $d:h /usr/bin /bin . )
   rehash
   dmake -v >>& /dev/null
   if ($status == 0) then
      strings $d |& grep $sys >>& /dev/null
      if ($status == 0) then
         pushd $d:h >>& /dev/null
         set mk = $cwd/dmake
         popd >>& /dev/null
         @ err = 0
         break
      endif
   endif
end

echo "$mk"

exit($err)
