#!/bin/csh -f
#
# BSYNT - SCHEME Basis syntax tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCHEME Basis Syntax Test ..... "
set exe = $BinDir/scheme

   if (($do_syntax == 0) && (-d $RootDir/scheme/syntax/m)) then
      NoteD $Log ""
      NoteD $Log -n "                    $msg"
      Note $Log ""

      flog $Log cp $FilesDir/shmtst.m .

      set opt = ( -l shmtst.m )
      if ("$Valgrind" == "") then
         $CFE $exe -e $opt >! shmtst.res
         set xstatus = $status
         if ($xstatus == 0) then
            diff shmtst.res $FilesDir/ref/shmtst >! shmtst.res.diff
            set xstatus = $status
         endif
      else
         ftee $Log $Valgrind $exe -e $opt      |& \
         grep "ERROR SUMMARY:"                 |& \
         awk '{ print $4 }'   >&! $Tmp
         set xstatus = `cat $Tmp`
         set rpf     = ( $rpf $Tmp )
      endif

$TEST_CHECK part -a bsynt -e $xstatus -rpf "$rpf" none

exit($status)
