#!/bin/csh -f
#
# COMMON - support for SCHEME test scripts
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

setenv Package  scheme
setenv Test     $0:t
source ../../../scripts/test-env

set shopt = ( -e )

if ("$CROSS_FE" == "") then
   set cross_fe = ""
else
   set cross_fe = ( $CROSS_FE -v )
endif

set do_syntax = 0

