#!/bin/csh -f
#
# MEM - SCHEME memory tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCHEME Memory Test ..........."
set exe = $BinDir/scheme
set opt = ( $shopt -l $FilesDir/mmtst.scm )
set io  = flog

   NoteD $Log ""
   NoteD $Log -n "                    $msg"
   Note $Log ""

   flog $Log pwd
   flog $Log cp $FilesDir/mmtst.scm .

   source ../../../scripts/test-run

   set rpf = ( $rpf '#tmp#' mmtst.scm )

$TEST_CHECK part -a mem -e $xstatus -dt $dt -rpf "$rpf" none

exit($status)
