#!/bin/csh -f
#
# PROC - SCHEME process tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

set msg = "SCHEME Proc Test ............. "
set exe = $BinDir/scheme
set opt = ( -e -l $FilesDir/shproc.scm )
set io  = shproc.res

   if (($CROSS_COMPILE == FALSE) && ($HaveIPC == YES)) then
      NoteD $Log ""
      NoteD $Log -n "                    $msg"
      Note $Log ""

      source ../../../scripts/test-run

      set rpf = ( $rpf shproc.res shproc.res.diff )
   endif

$TEST_CHECK part -a proc -e $xstatus -dt $dt -rpf "$rpf" none

exit($status)
