;
; SHCPX.SCM - test complex and quaternion types
;
; Source Version: 3.0
; Software Release #: LLNL-CODE-422942
;
; include "cpyright.h"
;

;--------------------------------------------------------------------------
;--------------------------------------------------------------------------

(define a (make-rectangular 1 -2))

(printf nil "Cartesian complex test\n")
(define z (make-rectangular 3 4))
(printf nil "z = %s\n" z)
(printf nil "a = %s\n" a)
(printf nil "real(z)      = %g\n" (real-part z))
(printf nil "imag(z)      = %g\n" (imag-part z))
(printf nil "magnitude(z) = %g\n" (magnitude z))
(printf nil "angle(z)     = %g\n" (angle z))
(printf nil "a+z          = %s\n" (+ a z))
(printf nil "a-z          = %s\n" (- a z))
(printf nil "a*z          = %s\n" (* a z))
(printf nil "a/z          = %s\n" (/ a z))
(printf nil "exp(z)       = %s\n" (exp z))
(printf nil "ln(z)        = %s\n" (ln z))
(printf nil "cos(z)       = %s\n" (cos z))
(printf nil "sin(z)       = %s\n" (sin z))
(printf nil "tan(z)       = %s\n" (tan z))
(printf nil "cot(z)       = %s\n" (cot z))
(printf nil "cosh(z)      = %s\n" (cosh z))
(printf nil "sinh(z)      = %s\n" (sinh z))
(printf nil "tanh(z)      = %s\n" (tanh z))
(printf nil "coth(z)      = %s\n" (coth z))
(printf nil "acos(z)      = %s\n" (acos z))
(printf nil "asin(z)      = %s\n" (asin z))
(printf nil "atan(z)      = %s\n" (atan z))
(printf nil "acosh(z)     = %s\n" (acosh z))
(printf nil "asinh(z)     = %s\n" (asinh z))
(printf nil "atanh(z)     = %s\n" (atanh z))
(printf nil "j0(z)        = %s\n" (j0 z))
(printf nil "j1(z)        = %s\n" (j1 z))
(printf nil "jn(z, 3)     = %s\n" (jn z 3))
(printf nil "k0(z)        = %s\n" (k0 z))
(printf nil "k1(z)        = %s\n" (k1 z))
(printf nil "kn(z, 3)     = %s\n" (kn z 3))
(printf nil "i0(z)        = %s\n" (i0 z))
(printf nil "i1(z)        = %s\n" (i1 z))
(printf nil "in(z, 3)     = %s\n" (in z 3))
(printf nil "y0(z)        = %s\n" (y0 z))
(printf nil "y1(z)        = %s\n" (y1 z))
(printf nil "yn(z, 3)     = %s\n" (yn z 3))
(printf nil "tchn(z, 3)   = %s\n" (tchn z 3))
(printf nil "\n")

(printf nil "Polar complex test\n")
(define z (make-polar 5 0.707))
(printf nil "z = %s\n" z)
(printf nil "a = %s\n" a)
(printf nil "real(z)      = %g\n" (real-part z))
(printf nil "imag(z)      = %g\n" (imag-part z))
(printf nil "magnitude(z) = %g\n" (magnitude z))
(printf nil "angle(z)     = %g\n" (angle z))
(printf nil "exp(z)       = %s\n" (exp z))
(printf nil "ln(z)        = %s\n" (ln z))
(printf nil "a+z          = %s\n" (+ a z))
(printf nil "a-z          = %s\n" (- a z))
(printf nil "a*z          = %s\n" (* a z))
(printf nil "a/z          = %s\n" (/ a z))
(printf nil "exp(z)       = %s\n" (exp z))
(printf nil "ln(z)        = %s\n" (ln z))
(printf nil "cos(z)       = %s\n" (cos z))
(printf nil "sin(z)       = %s\n" (sin z))
(printf nil "tan(z)       = %s\n" (tan z))
(printf nil "cot(z)       = %s\n" (cot z))
(printf nil "cosh(z)      = %s\n" (cosh z))
(printf nil "sinh(z)      = %s\n" (sinh z))
(printf nil "tanh(z)      = %s\n" (tanh z))
(printf nil "coth(z)      = %s\n" (coth z))
(printf nil "acos(z)      = %s\n" (acos z))
(printf nil "asin(z)      = %s\n" (asin z))
(printf nil "atan(z)      = %s\n" (atan z))
(printf nil "acosh(z)     = %s\n" (acosh z))
(printf nil "asinh(z)     = %s\n" (asinh z))
(printf nil "atanh(z)     = %s\n" (atanh z))
(printf nil "j0(z)        = %s\n" (j0 z))
(printf nil "j1(z)        = %s\n" (j1 z))
(printf nil "jn(z, 3)     = %s\n" (jn z 3))
(printf nil "k0(z)        = %s\n" (k0 z))
(printf nil "k1(z)        = %s\n" (k1 z))
(printf nil "kn(z, 3)     = %s\n" (kn z 3))
(printf nil "i0(z)        = %s\n" (i0 z))
(printf nil "i1(z)        = %s\n" (i1 z))
(printf nil "in(z, 3)     = %s\n" (in z 3))
(printf nil "y0(z)        = %s\n" (y0 z))
(printf nil "y1(z)        = %s\n" (y1 z))
(printf nil "yn(z, 3)     = %s\n" (yn z 3))
(printf nil "tchn(z, 3)   = %s\n" (tchn z 3))
(printf nil "\n")

;--------------------------------------------------------------------------
;--------------------------------------------------------------------------

(define b (make-rectangularq 1 -2 3 -4))

(printf nil "Cartesian quaternion test\n")
(define q (make-rectangularq 1 2 3 4))
(printf nil "q = %s\n" q)
(printf nil "b = %s\n" b)
(printf nil "scalar part(q) = %g\n" (real-partq q))
(printf nil "i part(q)      = %g\n" (imag-partq q))
(printf nil "j part(q)      = %g\n" (jmag-partq q))
(printf nil "k part(q)      = %g\n" (kmag-partq q))
(printf nil "magnitude(q)   = %g\n" (magnitudeq q))
(printf nil "angle(q)       = %g\n" (angleq q))
(printf nil "colatitude(q)  = %g\n" (colatitudeq q))
(printf nil "longitude(q)   = %g\n" (longitudeq q))
(printf nil "versor(q)      = %s\n" (versor q))
(printf nil "b+q            = %s\n" (+ b q))
(printf nil "b-q            = %s\n" (- b q))
(printf nil "b*q            = %s\n" (* b q))
(printf nil "b/q            = %s\n" (/ b q))
(printf nil "exp(q)         = %s\n" (exp q))
(printf nil "ln(q)          = %s\n" (ln q))
(printf nil "cos(q)         = %s\n" (cos q))
(printf nil "sin(q)         = %s\n" (sin q))
(printf nil "tan(q)         = %s\n" (tan q))
(printf nil "cot(q)         = %s\n" (cot q))
(printf nil "cosh(q)        = %s\n" (cosh q))
(printf nil "sinh(q)        = %s\n" (sinh q))
(printf nil "tanh(q)        = %s\n" (tanh q))
(printf nil "coth(q)        = %s\n" (coth q))
(printf nil "acos(q)        = %s\n" (acos q))
(printf nil "asin(q)        = %s\n" (asin q))
(printf nil "atan(q)        = %s\n" (atan q))
(printf nil "acosh(q)       = %s\n" (acosh q))
(printf nil "asinh(q)       = %s\n" (asinh q))
(printf nil "atanh(q)       = %s\n" (atanh q))
(printf nil "j0(q)          = %s\n" (j0 q))
(printf nil "j1(q)          = %s\n" (j1 q))
(printf nil "jn(q, 3)       = %s\n" (jn q 3))
(printf nil "k0(q)          = %s\n" (k0 q))
(printf nil "k1(q)          = %s\n" (k1 q))
(printf nil "kn(q, 3)       = %s\n" (kn q 3))
(printf nil "i0(q)          = %s\n" (i0 q))
(printf nil "i1(q)          = %s\n" (i1 q))
(printf nil "in(q, 3)       = %s\n" (in q 3))
(printf nil "y0(q)          = %s\n" (y0 q))
(printf nil "y1(q)          = %s\n" (y1 q))
(printf nil "yn(q, 3)       = %s\n" (yn q 3))
(printf nil "tchn(q, 3)     = %s\n" (tchn q 3))
(printf nil "\n")

(printf nil "Polar quaternion test\n")
(define q (make-polarq 1 0.1 0.2 0.3))
(printf nil "q = %s\n" q)
(printf nil "b = %s\n" b)
(printf nil "scalar part(q) = %g\n" (real-partq q))
(printf nil "i part(q)      = %g\n" (imag-partq q))
(printf nil "j part(q)      = %g\n" (jmag-partq q))
(printf nil "k part(q)      = %g\n" (kmag-partq q))
(printf nil "magnitude(q)   = %g\n" (magnitudeq q))
(printf nil "angle(q)       = %g\n" (angleq q))
(printf nil "colatitude(q)  = %g\n" (colatitudeq q))
(printf nil "longitude(q)   = %g\n" (longitudeq q))
(printf nil "versor(q)      = %s\n" (versor q))
(printf nil "b+q            = %s\n" (+ b q))
(printf nil "b-q            = %s\n" (- b q))
(printf nil "b*q            = %s\n" (* b q))
(printf nil "b/q            = %s\n" (/ b q))
(printf nil "exp(q)         = %s\n" (exp q))
(printf nil "ln(q)          = %s\n" (ln q))
(printf nil "cos(q)         = %s\n" (cos q))
(printf nil "sin(q)         = %s\n" (sin q))
(printf nil "tan(q)         = %s\n" (tan q))
(printf nil "cot(q)         = %s\n" (cot q))
(printf nil "cosh(q)        = %s\n" (cosh q))
(printf nil "sinh(q)        = %s\n" (sinh q))
(printf nil "tanh(q)        = %s\n" (tanh q))
(printf nil "coth(q)        = %s\n" (coth q))
(printf nil "acos(q)        = %s\n" (acos q))
(printf nil "asin(q)        = %s\n" (asin q))
(printf nil "atan(q)        = %s\n" (atan q))
(printf nil "acosh(q)       = %s\n" (acosh q))
(printf nil "asinh(q)       = %s\n" (asinh q))
(printf nil "atanh(q)       = %s\n" (atanh q))
(printf nil "j0(q)          = %s\n" (j0 q))
(printf nil "j1(q)          = %s\n" (j1 q))
(printf nil "jn(q, 3)       = %s\n" (jn q 3))
(printf nil "k0(q)          = %s\n" (k0 q))
(printf nil "k1(q)          = %s\n" (k1 q))
(printf nil "kn(q, 3)       = %s\n" (kn q 3))
(printf nil "i0(q)          = %s\n" (i0 q))
(printf nil "i1(q)          = %s\n" (i1 q))
(printf nil "in(q, 3)       = %s\n" (in q 3))
(printf nil "y0(q)          = %s\n" (y0 q))
(printf nil "y1(q)          = %s\n" (y1 q))
(printf nil "yn(q, 3)       = %s\n" (yn q 3))
(printf nil "tchn(q, 3)     = %s\n" (tchn q 3))
(printf nil "\n")

;--------------------------------------------------------------------------
;--------------------------------------------------------------------------

(quit)
