#!/bin/csh -f
#
# SHELL - SCHEME shell tests
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

source ../../tests/common

#--------------------------------------------------------------------------

#                           SHELL TESTS

#--------------------------------------------------------------------------

   if (($CROSS_COMPILE == FALSE) && ($HaveIPC == YES)) then
      NoteD $Log ""
      NoteD $Log "                    SCHEME Shell Test"

      set UTime = `$TIMER -r`
      $CFE $FilesDir/shenv.scm >&! shenv.res
      set xstatus = $status
      diff shenv.res $FilesDir/ref/shenv >&! shenv.res.diff
      set dstatus = $status
      set ETime = `$TIMER -b $UTime`

      if (($xstatus != 0) || ($dstatus != 0)) then
         flog $Log cat shenv.res
         flog $Log cat shenv.res.diff
         set xstatus = 1
      endif
      if ($xstatus != 0) then
         NoteD $Log "                       env ....................... FAILED ($xstatus/$ETime)"
         set Err = 1
      else
         NoteD $Log "                       env ....................... PASSED ($ETime)"
         flog $Log rm -f shenv.res shenv.res.diff
      endif

      set UTime = `$TIMER -r`
      $CFE $FilesDir/shexe.scm a 1 2.3 '"abc"' >&! shexe.res
      set xstatus = $status
      diff shexe.res $FilesDir/ref/shexe >&! shexe.res.diff
      set dstatus = $status
      set ETime = `$TIMER -b $UTime`

      if (($xstatus != 0) || ($dstatus != 0)) then
         flog $Log cat shexe.res
         flog $Log cat shexe.res.diff
         set xstatus = 1
      endif
      if ($xstatus != 0) then
         NoteD $Log "                       argv ...................... FAILED ($xstatus/$ETime)"
         set Err = 1
      else
         NoteD $Log "                       argv ...................... PASSED ($ETime)"
         flog $Log rm -f shexe.res shexe.res.diff
      endif

   endif

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

exit($Err)
