#!/bin/csh -f
#
# EXT - test aexec
#

source ../../tests/common

set msg = "AEXEC Test ....................."

set AEXEC = aexec

set lst = ( job pipe file var )

while ($#argv > 0)
   switch ($1)
      case -h:
           echo ""
           echo "Usage: aexec [-h]"
           echo "  h  this help message"
           echo ""
           exit(1);
      default:
           breaksw
   endsw
   shift
end

   NoteD $Log ""
   NoteD $Log "                    $msg"

   @ nerr = 0

   flog $Log rm -f run.* s*
   flog $Log cp $SrcDir/tests/ext-* .

   Note $Log "Using $AEXEC"
   Note $Log "Path = $PATH"

   flog $Log pwd
   flog $Log ls -l ext-*

   foreach t ($lst)
      Separator $Log

      set f = ( `fill-string -n 28 $t` )
      NoteD $Log -n "                        $f"
      Note $Log ""

      set exe = $t
      set opt = ""
      set rpf = ""

      flog $Log ./ext-$t

      set rpf = ( $rpf ext-$t )

      $TEST_CHECK part -a aexec_${t} -e $xstatus -dt $dt -x $exe -l -rpf "$rpf" none
      @ nerr = $nerr + $status
   end

$TEST_CHECK part -a aexec -e $nerr -rpf "$rpf" "$msg"

exit($status)

