#!/bin/csh -f
#
# EXT-PIPE - test gexec with old shell pipe syntax
#

unalias *

@ err = 0

source $TestScrDir/env-csh

alias pe  'unsetenv gstatus ; echo "" ; echo "Command: \!*" ; gexec \!* ; dbget gstatus'

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

foreach i (1 2 3)

   echo ""
   echo "---------------------------------------------------"
   echo ""

   set id  = s$i
   set res = ext-$id.res
   set raw = $res.raw
   set dif = $res.dif
   set ref = $RefDir/ext-$id

   switch ($i)

# simple stdout variants
      case 1:
           set cmd = ( pe /bin/echo "$id" "'|'" cat -n >&! $res )
           set gst = "0 0"
           set srt = FALSE
           breaksw

# simple bonded stdout/stderr variants
      case 2:
           set cmd = ( pe ls 'ext-*' foo.h "'|'" cat -n >&! $raw )
           set gst = "2 0"
           set srt = TRUE
           breaksw
      case 3:
           set cmd = ( pe ls 'ext-*' foo.h "'|&'" cat -n >&! $raw )
           set gst = "2 0"
           set srt = TRUE
           breaksw
   endsw

   eval $cmd

   if ($srt == TRUE) then
      sort $raw >&! $res
      rm -f $raw
   endif

   cat $res

   echo "> gstatus = $gstatus"
   if ("$gstatus" != "$gst") then
      @ err = $err + 1
      echo "$id failed"
   else if (-f $ref) then
      diff $res $ref >&! $dif
      if ($status == 0) then
         echo "$id passed"
         rm -f $res $dif
      else
         echo "$id differed"
         cat $dif
      endif
   else
      cp $res $ref
      echo "$id added"
      rm -f $res
   endif

end

echo ""

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

exit($err)

