#!/bin/csh -f
#
# EXT-PIPE - test aexec with old shell pipe syntax
#

@ err = 0

alias pe  'echo "" ; echo "Command: \!*" ; aexec \!*'

#set echo 
#set verbose

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

echo "------------------------------------------------------------------------"
echo ""
echo "# simple stdout variants"

   pe '/bin/echo foo | cat -n'
   echo "status = $status"

echo ""
echo "------------------------------------------------------------------------"
echo ""
echo "# simple bonded stdout/stderr variants"

   pe 'ls ext-* foo.h | cat -n'
   echo "status = $status"

   pe 'ls ext-* foo.h |& cat -n'
   echo "status = $status"

#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

echo ""

exit($err)
