#!/bin/csh -f
#
# PERDB4 - test save command
#        - use environment variable specification of DB
#        - no FIFO
#

set opt = "-l"
set db  = ./db3

setenv PERDB_PATH $db

echo "-----------------------------------"
perdb $opt save: v1

echo "-----------------------------------"
perdb $opt save: v2

echo "-----------------------------------"
perdb $opt save intera: v1

echo "-----------------------------------"
perdb $opt save interb:

echo "-----------------------------------"
perdb $opt save:

echo "-----------------------------------"
perdb $opt quit:

exit($status)
