#!/bin/csh -f
#
# CC-NORETURN - analyze _Noreturn for C11 compiler
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#


set Me = $0
source $Me:h/pre-common

Note $ALog "----- analyze/cc-noreturn -----"
Note $ALog "Analyze: C11 _Noreturn handling"
Note $ALog ""

dbmget $ALog PACT_CC_VERSION

cat << EOF >! $Tmp.c
#include <unistd.h>
_Noreturn void b(void) {while (1) sleep(1);}
int main(int c, char **v)
   {b();
    return(0);}
EOF

flog $ALog $lCC $Tmp.c -o $Tmp
set xstatus = $status
if ($xstatus == 0) then
   setenv HAVE_NORETURN TRUE
   NoteD $ALog "      has _Noreturn support"
else
   Note $ALog ""
   Note $ALog "--Compilation failed--"
   Note $ALog "/* $lCC $Tmp.c -o $Tmp */"
   cat $Tmp.c >>& $ALog

   setenv HAVE_NORETURN FALSE
   NoteD $ALog "      no _Noreturn support"
endif

rm -f $Tmp $Tmp.c $Tmp.o

# export the result

dbexp HAVE_NORETURN

source $Me:h/post-common

exit(0)
