#!/bin/csh -f
#
# LIB64 - analyze 64-bit archive directories
#
# Source Version: 3.0
# Software Release #: LLNL-CODE-422942
#
# include "cpyright.h"
#

set lme   = $0
set lbase = $lme:h
source $lbase/pre-common

unalias file

set lQuiet = FALSE
while ($#argv > 0)
   switch ($1)
      case -q:
           set lQuiet = TRUE
           breaksw
   endsw
   shift
end

dbmget $ALog Bits^   \
             PATH

set lroot = /usr
source $lbase/common-lib64
unset lroot
setenv LIB $LibT

if ($lQuiet == FALSE) then
   NoteD $ALog "   Library base: $LIB"
endif

# export the results
dbexp LIB

source $lbase/post-common

exit(0)

